/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-RC-IEs"
 * 	found in "rc.asn1"
 * 	`asn1c -pdu=auto -fno-include-deps -fcompound-names -findirect-choice -gen-PER -gen-OER`
 */

#ifndef	_E2SM_RC_IndicationMessage_Format4_H_
#define	_E2SM_RC_IndicationMessage_Format4_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include "UEID.h"
#include <OCTET_STRING.h>
#include <constr_SEQUENCE.h>
#include <constr_SEQUENCE_OF.h>
#include "CGI.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct NeighborRelation_Info;

/* Forward definitions */
typedef struct E2SM_RC_IndicationMessage_Format4__ueInfo_List__Member {
	UEID_t	 ueID;
	OCTET_STRING_t	*ueContextInfo;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2SM_RC_IndicationMessage_Format4__ueInfo_List__Member;
typedef struct E2SM_RC_IndicationMessage_Format4__cellInfo_List__Member {
	CGI_t	 cellGlobal_ID;
	OCTET_STRING_t	*cellContextInfo;	/* OPTIONAL */
	struct NeighborRelation_Info	*neighborRelation_Table;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2SM_RC_IndicationMessage_Format4__cellInfo_List__Member;

/* E2SM-RC-IndicationMessage-Format4 */
typedef struct E2SM_RC_IndicationMessage_Format4 {
	struct E2SM_RC_IndicationMessage_Format4__ueInfo_List {
		A_SEQUENCE_OF(E2SM_RC_IndicationMessage_Format4__ueInfo_List__Member) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} ueInfo_List;
	struct E2SM_RC_IndicationMessage_Format4__cellInfo_List {
		A_SEQUENCE_OF(E2SM_RC_IndicationMessage_Format4__cellInfo_List__Member) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} cellInfo_List;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2SM_RC_IndicationMessage_Format4_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_E2SM_RC_IndicationMessage_Format4;
extern asn_SEQUENCE_specifics_t asn_SPC_E2SM_RC_IndicationMessage_Format4_specs_1;
extern asn_TYPE_member_t asn_MBR_E2SM_RC_IndicationMessage_Format4_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _E2SM_RC_IndicationMessage_Format4_H_ */
#include <asn_internal.h>
