/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-RC-IEs"
 * 	found in "rc.asn1"
 * 	`asn1c -pdu=auto -fno-include-deps -fcompound-names -findirect-choice -gen-PER -gen-OER`
 */

#ifndef	_E2SM_RC_EventTrigger_Format3_H_
#define	_E2SM_RC_EventTrigger_Format3_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include "RIC-EventTriggerCondition-ID.h"
#include <NativeInteger.h>
#include "LogicalOR.h"
#include <constr_SEQUENCE.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct EventTrigger_Cell_Info;

/* Forward definitions */
typedef struct E2SM_RC_EventTrigger_Format3__e2NodeInfoChange_List__Member {
	RIC_EventTriggerCondition_ID_t	 ric_eventTriggerCondition_ID;
	long	 e2NodeInfoChange_ID;
	struct EventTrigger_Cell_Info	*associatedCellInfo;	/* OPTIONAL */
	LogicalOR_t	*logicalOR;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2SM_RC_EventTrigger_Format3__e2NodeInfoChange_List__Member;

/* E2SM-RC-EventTrigger-Format3 */
typedef struct E2SM_RC_EventTrigger_Format3 {
	struct E2SM_RC_EventTrigger_Format3__e2NodeInfoChange_List {
		A_SEQUENCE_OF(E2SM_RC_EventTrigger_Format3__e2NodeInfoChange_List__Member) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} e2NodeInfoChange_List;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} E2SM_RC_EventTrigger_Format3_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_E2SM_RC_EventTrigger_Format3;
extern asn_SEQUENCE_specifics_t asn_SPC_E2SM_RC_EventTrigger_Format3_specs_1;
extern asn_TYPE_member_t asn_MBR_E2SM_RC_EventTrigger_Format3_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _E2SM_RC_EventTrigger_Format3_H_ */
#include <asn_internal.h>
