/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-RC-IEs"
 * 	found in "rc.asn1"
 * 	`asn1c -pdu=auto -fno-include-deps -fcompound-names -findirect-choice -gen-PER -gen-OER`
 */

#include "E2SM-RC-EventTrigger-Format4.h"

#include "EventTrigger-UE-Info.h"
#include "TriggerType-Choice-RRCstate.h"
#include "TriggerType-Choice-UEID.h"
#include "TriggerType-Choice-L2state.h"
static int
memb_uEInfoChange_List_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 65535)) {
		/* Perform validation of the inner elements */
		return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_type_triggerType_constr_5 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_triggerType_constr_5 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  2,  2,  0,  2 }	/* (0..2,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_uEInfoChange_List_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..65535)) */};
static asn_per_constraints_t asn_PER_type_uEInfoChange_List_constr_2 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_uEInfoChange_List_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..65535)) */};
static asn_per_constraints_t asn_PER_memb_uEInfoChange_List_constr_2 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_triggerType_5[] = {
	{ ATF_POINTER, 0, offsetof(struct E2SM_RC_EventTrigger_Format4__uEInfoChange_List__Member__triggerType, choice.triggerType_Choice_RRCstate),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TriggerType_Choice_RRCstate,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"triggerType-Choice-RRCstate"
		},
	{ ATF_POINTER, 0, offsetof(struct E2SM_RC_EventTrigger_Format4__uEInfoChange_List__Member__triggerType, choice.triggerType_Choice_UEID),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TriggerType_Choice_UEID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"triggerType-Choice-UEID"
		},
	{ ATF_POINTER, 0, offsetof(struct E2SM_RC_EventTrigger_Format4__uEInfoChange_List__Member__triggerType, choice.triggerType_Choice_L2state),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_TriggerType_Choice_L2state,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"triggerType-Choice-L2state"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_triggerType_tag2el_5[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* triggerType-Choice-RRCstate */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* triggerType-Choice-UEID */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* triggerType-Choice-L2state */
};
static asn_CHOICE_specifics_t asn_SPC_triggerType_specs_5 = {
	sizeof(struct E2SM_RC_EventTrigger_Format4__uEInfoChange_List__Member__triggerType),
	offsetof(struct E2SM_RC_EventTrigger_Format4__uEInfoChange_List__Member__triggerType, _asn_ctx),
	offsetof(struct E2SM_RC_EventTrigger_Format4__uEInfoChange_List__Member__triggerType, present),
	sizeof(((struct E2SM_RC_EventTrigger_Format4__uEInfoChange_List__Member__triggerType *)0)->present),
	asn_MAP_triggerType_tag2el_5,
	3,	/* Count of tags in the map */
	0, 0,
	3	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_triggerType_5 = {
	"triggerType",
	"triggerType",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_triggerType_constr_5, &asn_PER_type_triggerType_constr_5, CHOICE_constraint },
	asn_MBR_triggerType_5,
	3,	/* Elements count */
	&asn_SPC_triggerType_specs_5	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_Member_3[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct E2SM_RC_EventTrigger_Format4__uEInfoChange_List__Member, ric_eventTriggerCondition_ID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RIC_EventTriggerCondition_ID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ric-eventTriggerCondition-ID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct E2SM_RC_EventTrigger_Format4__uEInfoChange_List__Member, triggerType),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_triggerType_5,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"triggerType"
		},
	{ ATF_POINTER, 2, offsetof(struct E2SM_RC_EventTrigger_Format4__uEInfoChange_List__Member, associatedUEInfo),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EventTrigger_UE_Info,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"associatedUEInfo"
		},
	{ ATF_POINTER, 1, offsetof(struct E2SM_RC_EventTrigger_Format4__uEInfoChange_List__Member, logicalOR),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LogicalOR,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"logicalOR"
		},
};
static const int asn_MAP_Member_oms_3[] = { 2, 3 };
static const ber_tlv_tag_t asn_DEF_Member_tags_3[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Member_tag2el_3[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ric-eventTriggerCondition-ID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* triggerType */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* associatedUEInfo */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* logicalOR */
};
static asn_SEQUENCE_specifics_t asn_SPC_Member_specs_3 = {
	sizeof(struct E2SM_RC_EventTrigger_Format4__uEInfoChange_List__Member),
	offsetof(struct E2SM_RC_EventTrigger_Format4__uEInfoChange_List__Member, _asn_ctx),
	asn_MAP_Member_tag2el_3,
	4,	/* Count of tags in the map */
	asn_MAP_Member_oms_3,	/* Optional members */
	2, 0,	/* Root/Additions */
	4,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_Member_3 = {
	"SEQUENCE",
	"SEQUENCE",
	&asn_OP_SEQUENCE,
	asn_DEF_Member_tags_3,
	sizeof(asn_DEF_Member_tags_3)
		/sizeof(asn_DEF_Member_tags_3[0]), /* 1 */
	asn_DEF_Member_tags_3,	/* Same as above */
	sizeof(asn_DEF_Member_tags_3)
		/sizeof(asn_DEF_Member_tags_3[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Member_3,
	4,	/* Elements count */
	&asn_SPC_Member_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_uEInfoChange_List_2[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Member_3,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_uEInfoChange_List_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_uEInfoChange_List_specs_2 = {
	sizeof(struct E2SM_RC_EventTrigger_Format4__uEInfoChange_List),
	offsetof(struct E2SM_RC_EventTrigger_Format4__uEInfoChange_List, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_uEInfoChange_List_2 = {
	"uEInfoChange-List",
	"uEInfoChange-List",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_uEInfoChange_List_tags_2,
	sizeof(asn_DEF_uEInfoChange_List_tags_2)
		/sizeof(asn_DEF_uEInfoChange_List_tags_2[0]) - 1, /* 1 */
	asn_DEF_uEInfoChange_List_tags_2,	/* Same as above */
	sizeof(asn_DEF_uEInfoChange_List_tags_2)
		/sizeof(asn_DEF_uEInfoChange_List_tags_2[0]), /* 2 */
	{ &asn_OER_type_uEInfoChange_List_constr_2, &asn_PER_type_uEInfoChange_List_constr_2, SEQUENCE_OF_constraint },
	asn_MBR_uEInfoChange_List_2,
	1,	/* Single element */
	&asn_SPC_uEInfoChange_List_specs_2	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_E2SM_RC_EventTrigger_Format4_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct E2SM_RC_EventTrigger_Format4, uEInfoChange_List),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_uEInfoChange_List_2,
		0,
		{ &asn_OER_memb_uEInfoChange_List_constr_2, &asn_PER_memb_uEInfoChange_List_constr_2,  memb_uEInfoChange_List_constraint_1 },
		0, 0, /* No default value */
		"uEInfoChange-List"
		},
};
static const ber_tlv_tag_t asn_DEF_E2SM_RC_EventTrigger_Format4_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_E2SM_RC_EventTrigger_Format4_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* uEInfoChange-List */
};
asn_SEQUENCE_specifics_t asn_SPC_E2SM_RC_EventTrigger_Format4_specs_1 = {
	sizeof(struct E2SM_RC_EventTrigger_Format4),
	offsetof(struct E2SM_RC_EventTrigger_Format4, _asn_ctx),
	asn_MAP_E2SM_RC_EventTrigger_Format4_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_E2SM_RC_EventTrigger_Format4 = {
	"E2SM-RC-EventTrigger-Format4",
	"E2SM-RC-EventTrigger-Format4",
	&asn_OP_SEQUENCE,
	asn_DEF_E2SM_RC_EventTrigger_Format4_tags_1,
	sizeof(asn_DEF_E2SM_RC_EventTrigger_Format4_tags_1)
		/sizeof(asn_DEF_E2SM_RC_EventTrigger_Format4_tags_1[0]), /* 1 */
	asn_DEF_E2SM_RC_EventTrigger_Format4_tags_1,	/* Same as above */
	sizeof(asn_DEF_E2SM_RC_EventTrigger_Format4_tags_1)
		/sizeof(asn_DEF_E2SM_RC_EventTrigger_Format4_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_E2SM_RC_EventTrigger_Format4_1,
	1,	/* Elements count */
	&asn_SPC_E2SM_RC_EventTrigger_Format4_specs_1	/* Additional specs */
};

