/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-RC-IEs"
 * 	found in "rc.asn1"
 * 	`asn1c -pdu=auto -fno-include-deps -fcompound-names -findirect-choice -gen-PER -gen-OER`
 */

#include "E2SM-RC-EventTrigger-Format1.h"

#include "EventTrigger-UE-Info.h"
#include "EventTrigger-UEevent-Info.h"
#include "MessageType-Choice-NI.h"
#include "MessageType-Choice-RRC.h"
/*
 * This type is implemented using NativeEnumerated,
 * so here we adjust the DEF accordingly.
 */
static int
memb_message_List_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 65535)) {
		/* Perform validation of the inner elements */
		return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_type_messageType_constr_5 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_messageType_constr_5 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  1,  1,  0,  1 }	/* (0..1,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_messageDirection_constr_9 CC_NOTUSED = {
	{ 0, 0 },
	-1};
static asn_per_constraints_t asn_PER_type_messageDirection_constr_9 CC_NOTUSED = {
	{ APC_CONSTRAINED | APC_EXTENSIBLE,  1,  1,  0,  1 }	/* (0..1,...) */,
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_message_List_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..65535)) */};
static asn_per_constraints_t asn_PER_type_message_List_constr_2 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_message_List_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..65535)) */};
static asn_per_constraints_t asn_PER_memb_message_List_constr_2 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_messageType_5[] = {
	{ ATF_POINTER, 0, offsetof(struct E2SM_RC_EventTrigger_Format1__message_List__Member__messageType, choice.messageType_Choice_NI),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MessageType_Choice_NI,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"messageType-Choice-NI"
		},
	{ ATF_POINTER, 0, offsetof(struct E2SM_RC_EventTrigger_Format1__message_List__Member__messageType, choice.messageType_Choice_RRC),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_MessageType_Choice_RRC,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"messageType-Choice-RRC"
		},
};
static const asn_TYPE_tag2member_t asn_MAP_messageType_tag2el_5[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* messageType-Choice-NI */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* messageType-Choice-RRC */
};
static asn_CHOICE_specifics_t asn_SPC_messageType_specs_5 = {
	sizeof(struct E2SM_RC_EventTrigger_Format1__message_List__Member__messageType),
	offsetof(struct E2SM_RC_EventTrigger_Format1__message_List__Member__messageType, _asn_ctx),
	offsetof(struct E2SM_RC_EventTrigger_Format1__message_List__Member__messageType, present),
	sizeof(((struct E2SM_RC_EventTrigger_Format1__message_List__Member__messageType *)0)->present),
	asn_MAP_messageType_tag2el_5,
	2,	/* Count of tags in the map */
	0, 0,
	2	/* Extensions start */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_messageType_5 = {
	"messageType",
	"messageType",
	&asn_OP_CHOICE,
	0,	/* No effective tags (pointer) */
	0,	/* No effective tags (count) */
	0,	/* No tags (pointer) */
	0,	/* No tags (count) */
	{ &asn_OER_type_messageType_constr_5, &asn_PER_type_messageType_constr_5, CHOICE_constraint },
	asn_MBR_messageType_5,
	2,	/* Elements count */
	&asn_SPC_messageType_specs_5	/* Additional specs */
};

static const asn_INTEGER_enum_map_t asn_MAP_messageDirection_value2enum_9[] = {
	{ 0,	8,	"incoming" },
	{ 1,	8,	"outgoing" }
	/* This list is extensible */
};
static const unsigned int asn_MAP_messageDirection_enum2value_9[] = {
	0,	/* incoming(0) */
	1	/* outgoing(1) */
	/* This list is extensible */
};
static const asn_INTEGER_specifics_t asn_SPC_messageDirection_specs_9 = {
	asn_MAP_messageDirection_value2enum_9,	/* "tag" => N; sorted by tag */
	asn_MAP_messageDirection_enum2value_9,	/* N => "tag"; sorted by N */
	2,	/* Number of elements in the maps */
	3,	/* Extensions before this member */
	1,	/* Strict enumeration */
	0,	/* Native long size */
	0
};
static const ber_tlv_tag_t asn_DEF_messageDirection_tags_9[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (10 << 2))
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_messageDirection_9 = {
	"messageDirection",
	"messageDirection",
	&asn_OP_NativeEnumerated,
	asn_DEF_messageDirection_tags_9,
	sizeof(asn_DEF_messageDirection_tags_9)
		/sizeof(asn_DEF_messageDirection_tags_9[0]) - 1, /* 1 */
	asn_DEF_messageDirection_tags_9,	/* Same as above */
	sizeof(asn_DEF_messageDirection_tags_9)
		/sizeof(asn_DEF_messageDirection_tags_9[0]), /* 2 */
	{ &asn_OER_type_messageDirection_constr_9, &asn_PER_type_messageDirection_constr_9, NativeEnumerated_constraint },
	0, 0,	/* Defined elsewhere */
	&asn_SPC_messageDirection_specs_9	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_Member_3[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct E2SM_RC_EventTrigger_Format1__message_List__Member, ric_eventTriggerCondition_ID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RIC_EventTriggerCondition_ID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ric-eventTriggerCondition-ID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct E2SM_RC_EventTrigger_Format1__message_List__Member, messageType),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		+1,	/* EXPLICIT tag at current level */
		&asn_DEF_messageType_5,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"messageType"
		},
	{ ATF_POINTER, 4, offsetof(struct E2SM_RC_EventTrigger_Format1__message_List__Member, messageDirection),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_messageDirection_9,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"messageDirection"
		},
	{ ATF_POINTER, 3, offsetof(struct E2SM_RC_EventTrigger_Format1__message_List__Member, associatedUEInfo),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EventTrigger_UE_Info,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"associatedUEInfo"
		},
	{ ATF_POINTER, 2, offsetof(struct E2SM_RC_EventTrigger_Format1__message_List__Member, associatedUEEvent),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EventTrigger_UEevent_Info,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"associatedUEEvent"
		},
	{ ATF_POINTER, 1, offsetof(struct E2SM_RC_EventTrigger_Format1__message_List__Member, logicalOR),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_LogicalOR,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"logicalOR"
		},
};
static const int asn_MAP_Member_oms_3[] = { 2, 3, 4, 5 };
static const ber_tlv_tag_t asn_DEF_Member_tags_3[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Member_tag2el_3[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ric-eventTriggerCondition-ID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* messageType */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* messageDirection */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* associatedUEInfo */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* associatedUEEvent */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 } /* logicalOR */
};
static asn_SEQUENCE_specifics_t asn_SPC_Member_specs_3 = {
	sizeof(struct E2SM_RC_EventTrigger_Format1__message_List__Member),
	offsetof(struct E2SM_RC_EventTrigger_Format1__message_List__Member, _asn_ctx),
	asn_MAP_Member_tag2el_3,
	6,	/* Count of tags in the map */
	asn_MAP_Member_oms_3,	/* Optional members */
	4, 0,	/* Root/Additions */
	6,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_Member_3 = {
	"SEQUENCE",
	"SEQUENCE",
	&asn_OP_SEQUENCE,
	asn_DEF_Member_tags_3,
	sizeof(asn_DEF_Member_tags_3)
		/sizeof(asn_DEF_Member_tags_3[0]), /* 1 */
	asn_DEF_Member_tags_3,	/* Same as above */
	sizeof(asn_DEF_Member_tags_3)
		/sizeof(asn_DEF_Member_tags_3[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Member_3,
	6,	/* Elements count */
	&asn_SPC_Member_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_message_List_2[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Member_3,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_message_List_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_message_List_specs_2 = {
	sizeof(struct E2SM_RC_EventTrigger_Format1__message_List),
	offsetof(struct E2SM_RC_EventTrigger_Format1__message_List, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_message_List_2 = {
	"message-List",
	"message-List",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_message_List_tags_2,
	sizeof(asn_DEF_message_List_tags_2)
		/sizeof(asn_DEF_message_List_tags_2[0]) - 1, /* 1 */
	asn_DEF_message_List_tags_2,	/* Same as above */
	sizeof(asn_DEF_message_List_tags_2)
		/sizeof(asn_DEF_message_List_tags_2[0]), /* 2 */
	{ &asn_OER_type_message_List_constr_2, &asn_PER_type_message_List_constr_2, SEQUENCE_OF_constraint },
	asn_MBR_message_List_2,
	1,	/* Single element */
	&asn_SPC_message_List_specs_2	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_E2SM_RC_EventTrigger_Format1_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct E2SM_RC_EventTrigger_Format1, message_List),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_message_List_2,
		0,
		{ &asn_OER_memb_message_List_constr_2, &asn_PER_memb_message_List_constr_2,  memb_message_List_constraint_1 },
		0, 0, /* No default value */
		"message-List"
		},
	{ ATF_POINTER, 1, offsetof(struct E2SM_RC_EventTrigger_Format1, globalAssociatedUEInfo),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_EventTrigger_UE_Info,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"globalAssociatedUEInfo"
		},
};
static const int asn_MAP_E2SM_RC_EventTrigger_Format1_oms_1[] = { 1 };
static const ber_tlv_tag_t asn_DEF_E2SM_RC_EventTrigger_Format1_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_E2SM_RC_EventTrigger_Format1_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* message-List */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* globalAssociatedUEInfo */
};
asn_SEQUENCE_specifics_t asn_SPC_E2SM_RC_EventTrigger_Format1_specs_1 = {
	sizeof(struct E2SM_RC_EventTrigger_Format1),
	offsetof(struct E2SM_RC_EventTrigger_Format1, _asn_ctx),
	asn_MAP_E2SM_RC_EventTrigger_Format1_tag2el_1,
	2,	/* Count of tags in the map */
	asn_MAP_E2SM_RC_EventTrigger_Format1_oms_1,	/* Optional members */
	1, 0,	/* Root/Additions */
	2,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_E2SM_RC_EventTrigger_Format1 = {
	"E2SM-RC-EventTrigger-Format1",
	"E2SM-RC-EventTrigger-Format1",
	&asn_OP_SEQUENCE,
	asn_DEF_E2SM_RC_EventTrigger_Format1_tags_1,
	sizeof(asn_DEF_E2SM_RC_EventTrigger_Format1_tags_1)
		/sizeof(asn_DEF_E2SM_RC_EventTrigger_Format1_tags_1[0]), /* 1 */
	asn_DEF_E2SM_RC_EventTrigger_Format1_tags_1,	/* Same as above */
	sizeof(asn_DEF_E2SM_RC_EventTrigger_Format1_tags_1)
		/sizeof(asn_DEF_E2SM_RC_EventTrigger_Format1_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_E2SM_RC_EventTrigger_Format1_1,
	2,	/* Elements count */
	&asn_SPC_E2SM_RC_EventTrigger_Format1_specs_1	/* Additional specs */
};

