/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 */

struct asn_TYPE_descriptor_s;	/* Forward declaration */

extern struct asn_TYPE_descriptor_s asn_DEF_CoreCPID;
extern struct asn_TYPE_descriptor_s asn_DEF_GroupID;
extern struct asn_TYPE_descriptor_s asn_DEF_QoSID;
extern struct asn_TYPE_descriptor_s asn_DEF_SubscriberProfileIDforRFP;
extern struct asn_TYPE_descriptor_s asn_DEF_IndexToRFSP;
extern struct asn_TYPE_descriptor_s asn_DEF_QosFlowIdentifier;
extern struct asn_TYPE_descriptor_s asn_DEF_S_NSSAI;
extern struct asn_TYPE_descriptor_s asn_DEF_E2SM_RC_EventTrigger;
extern struct asn_TYPE_descriptor_s asn_DEF_E2SM_RC_ActionDefinition;
extern struct asn_TYPE_descriptor_s asn_DEF_E2SM_RC_IndicationHeader;
extern struct asn_TYPE_descriptor_s asn_DEF_E2SM_RC_IndicationMessage;
extern struct asn_TYPE_descriptor_s asn_DEF_E2SM_RC_CallProcessID;
extern struct asn_TYPE_descriptor_s asn_DEF_E2SM_RC_ControlHeader;
extern struct asn_TYPE_descriptor_s asn_DEF_E2SM_RC_ControlMessage;
extern struct asn_TYPE_descriptor_s asn_DEF_E2SM_RC_ControlOutcome;
extern struct asn_TYPE_descriptor_s asn_DEF_E2SM_RC_RANFunctionDefinition;


struct asn_TYPE_descriptor_s *asn_pdu_collection[] = {
	/* From module E2SM-COMMON-IEs in e2sm.asn1 */
	&asn_DEF_CoreCPID,	
	&asn_DEF_GroupID,	
	&asn_DEF_QoSID,	
	&asn_DEF_SubscriberProfileIDforRFP,	
	&asn_DEF_IndexToRFSP,	
	&asn_DEF_QosFlowIdentifier,	
	&asn_DEF_S_NSSAI,	
	/* From module E2SM-RC-IEs in rc.asn1 */
	&asn_DEF_E2SM_RC_EventTrigger,	
	&asn_DEF_E2SM_RC_ActionDefinition,	
	&asn_DEF_E2SM_RC_IndicationHeader,	
	&asn_DEF_E2SM_RC_IndicationMessage,	
	&asn_DEF_E2SM_RC_CallProcessID,	
	&asn_DEF_E2SM_RC_ControlHeader,	
	&asn_DEF_E2SM_RC_ControlMessage,	
	&asn_DEF_E2SM_RC_ControlOutcome,	
	&asn_DEF_E2SM_RC_RANFunctionDefinition,	
	0
};

