/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-RC-IEs"
 * 	found in "rc.asn1"
 * 	`asn1c -pdu=auto -fno-include-deps -fcompound-names -findirect-choice -gen-PER -gen-OER`
 */

#include "RANFunctionDefinition-EventTrigger.h"

static int
memb_ran_CallProcessBreakpointParameters_List_constraint_18(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 65535)) {
		/* Perform validation of the inner elements */
		return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_callProcessBreakpoints_List_constraint_14(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 65535)) {
		/* Perform validation of the inner elements */
		return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_ric_EventTriggerStyle_List_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 63)) {
		/* Perform validation of the inner elements */
		return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_ran_L2Parameters_List_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 65535)) {
		/* Perform validation of the inner elements */
		return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_ran_CallProcessTypes_List_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 65535)) {
		/* Perform validation of the inner elements */
		return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_ran_UEIdentificationParameters_List_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 65535)) {
		/* Perform validation of the inner elements */
		return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_ran_CellIdentificationParameters_List_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 65535)) {
		/* Perform validation of the inner elements */
		return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_type_ric_EventTriggerStyle_List_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..63)) */};
static asn_per_constraints_t asn_PER_type_ric_EventTriggerStyle_List_constr_2 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 6,  6,  1,  63 }	/* (SIZE(1..63)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ran_L2Parameters_List_constr_8 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..65535)) */};
static asn_per_constraints_t asn_PER_type_ran_L2Parameters_List_constr_8 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ran_CallProcessBreakpointParameters_List_constr_21 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..65535)) */};
static asn_per_constraints_t asn_PER_type_ran_CallProcessBreakpointParameters_List_constr_21 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_ran_CallProcessBreakpointParameters_List_constr_21 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..65535)) */};
static asn_per_constraints_t asn_PER_memb_ran_CallProcessBreakpointParameters_List_constr_21 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_callProcessBreakpoints_List_constr_17 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..65535)) */};
static asn_per_constraints_t asn_PER_type_callProcessBreakpoints_List_constr_17 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_callProcessBreakpoints_List_constr_17 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..65535)) */};
static asn_per_constraints_t asn_PER_memb_callProcessBreakpoints_List_constr_17 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ran_CallProcessTypes_List_constr_13 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..65535)) */};
static asn_per_constraints_t asn_PER_type_ran_CallProcessTypes_List_constr_13 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ran_UEIdentificationParameters_List_constr_28 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..65535)) */};
static asn_per_constraints_t asn_PER_type_ran_UEIdentificationParameters_List_constr_28 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ran_CellIdentificationParameters_List_constr_33 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..65535)) */};
static asn_per_constraints_t asn_PER_type_ran_CellIdentificationParameters_List_constr_33 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_ric_EventTriggerStyle_List_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..63)) */};
static asn_per_constraints_t asn_PER_memb_ric_EventTriggerStyle_List_constr_2 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 6,  6,  1,  63 }	/* (SIZE(1..63)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_ran_L2Parameters_List_constr_8 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..65535)) */};
static asn_per_constraints_t asn_PER_memb_ran_L2Parameters_List_constr_8 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_ran_CallProcessTypes_List_constr_13 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..65535)) */};
static asn_per_constraints_t asn_PER_memb_ran_CallProcessTypes_List_constr_13 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_ran_UEIdentificationParameters_List_constr_28 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..65535)) */};
static asn_per_constraints_t asn_PER_memb_ran_UEIdentificationParameters_List_constr_28 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_ran_CellIdentificationParameters_List_constr_33 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..65535)) */};
static asn_per_constraints_t asn_PER_memb_ran_CellIdentificationParameters_List_constr_33 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_Member_3[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RANFunctionDefinition_EventTrigger__ric_EventTriggerStyle_List__Member, ric_EventTriggerStyle_Type),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RIC_Style_Type,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ric-EventTriggerStyle-Type"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RANFunctionDefinition_EventTrigger__ric_EventTriggerStyle_List__Member, ric_EventTriggerStyle_Name),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RIC_Style_Name,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ric-EventTriggerStyle-Name"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RANFunctionDefinition_EventTrigger__ric_EventTriggerStyle_List__Member, ric_EventTriggerFormat_Type),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RIC_Format_Type,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ric-EventTriggerFormat-Type"
		},
};
static const ber_tlv_tag_t asn_DEF_Member_tags_3[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Member_tag2el_3[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ric-EventTriggerStyle-Type */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* ric-EventTriggerStyle-Name */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* ric-EventTriggerFormat-Type */
};
static asn_SEQUENCE_specifics_t asn_SPC_Member_specs_3 = {
	sizeof(struct RANFunctionDefinition_EventTrigger__ric_EventTriggerStyle_List__Member),
	offsetof(struct RANFunctionDefinition_EventTrigger__ric_EventTriggerStyle_List__Member, _asn_ctx),
	asn_MAP_Member_tag2el_3,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	3,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_Member_3 = {
	"SEQUENCE",
	"SEQUENCE",
	&asn_OP_SEQUENCE,
	asn_DEF_Member_tags_3,
	sizeof(asn_DEF_Member_tags_3)
		/sizeof(asn_DEF_Member_tags_3[0]), /* 1 */
	asn_DEF_Member_tags_3,	/* Same as above */
	sizeof(asn_DEF_Member_tags_3)
		/sizeof(asn_DEF_Member_tags_3[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Member_3,
	3,	/* Elements count */
	&asn_SPC_Member_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ric_EventTriggerStyle_List_2[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Member_3,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ric_EventTriggerStyle_List_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_ric_EventTriggerStyle_List_specs_2 = {
	sizeof(struct RANFunctionDefinition_EventTrigger__ric_EventTriggerStyle_List),
	offsetof(struct RANFunctionDefinition_EventTrigger__ric_EventTriggerStyle_List, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ric_EventTriggerStyle_List_2 = {
	"ric-EventTriggerStyle-List",
	"ric-EventTriggerStyle-List",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ric_EventTriggerStyle_List_tags_2,
	sizeof(asn_DEF_ric_EventTriggerStyle_List_tags_2)
		/sizeof(asn_DEF_ric_EventTriggerStyle_List_tags_2[0]) - 1, /* 1 */
	asn_DEF_ric_EventTriggerStyle_List_tags_2,	/* Same as above */
	sizeof(asn_DEF_ric_EventTriggerStyle_List_tags_2)
		/sizeof(asn_DEF_ric_EventTriggerStyle_List_tags_2[0]), /* 2 */
	{ &asn_OER_type_ric_EventTriggerStyle_List_constr_2, &asn_PER_type_ric_EventTriggerStyle_List_constr_2, SEQUENCE_OF_constraint },
	asn_MBR_ric_EventTriggerStyle_List_2,
	1,	/* Single element */
	&asn_SPC_ric_EventTriggerStyle_List_specs_2	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_Member_9[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RANFunctionDefinition_EventTrigger__ran_L2Parameters_List__Member, ranParameter_ID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANParameter_ID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ranParameter-ID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RANFunctionDefinition_EventTrigger__ran_L2Parameters_List__Member, ranParameter_Name),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANParameter_Name,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ranParameter-Name"
		},
};
static const ber_tlv_tag_t asn_DEF_Member_tags_9[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Member_tag2el_9[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ranParameter-ID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* ranParameter-Name */
};
static asn_SEQUENCE_specifics_t asn_SPC_Member_specs_9 = {
	sizeof(struct RANFunctionDefinition_EventTrigger__ran_L2Parameters_List__Member),
	offsetof(struct RANFunctionDefinition_EventTrigger__ran_L2Parameters_List__Member, _asn_ctx),
	asn_MAP_Member_tag2el_9,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_Member_9 = {
	"SEQUENCE",
	"SEQUENCE",
	&asn_OP_SEQUENCE,
	asn_DEF_Member_tags_9,
	sizeof(asn_DEF_Member_tags_9)
		/sizeof(asn_DEF_Member_tags_9[0]), /* 1 */
	asn_DEF_Member_tags_9,	/* Same as above */
	sizeof(asn_DEF_Member_tags_9)
		/sizeof(asn_DEF_Member_tags_9[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Member_9,
	2,	/* Elements count */
	&asn_SPC_Member_specs_9	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ran_L2Parameters_List_8[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Member_9,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ran_L2Parameters_List_tags_8[] = {
	(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_ran_L2Parameters_List_specs_8 = {
	sizeof(struct RANFunctionDefinition_EventTrigger__ran_L2Parameters_List),
	offsetof(struct RANFunctionDefinition_EventTrigger__ran_L2Parameters_List, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ran_L2Parameters_List_8 = {
	"ran-L2Parameters-List",
	"ran-L2Parameters-List",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ran_L2Parameters_List_tags_8,
	sizeof(asn_DEF_ran_L2Parameters_List_tags_8)
		/sizeof(asn_DEF_ran_L2Parameters_List_tags_8[0]) - 1, /* 1 */
	asn_DEF_ran_L2Parameters_List_tags_8,	/* Same as above */
	sizeof(asn_DEF_ran_L2Parameters_List_tags_8)
		/sizeof(asn_DEF_ran_L2Parameters_List_tags_8[0]), /* 2 */
	{ &asn_OER_type_ran_L2Parameters_List_constr_8, &asn_PER_type_ran_L2Parameters_List_constr_8, SEQUENCE_OF_constraint },
	asn_MBR_ran_L2Parameters_List_8,
	1,	/* Single element */
	&asn_SPC_ran_L2Parameters_List_specs_8	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_Member_22[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RANFunctionDefinition_EventTrigger__ran_CallProcessTypes_List__Member__callProcessBreakpoints_List__Member__ran_CallProcessBreakpointParameters_List__Member, ranParameter_ID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANParameter_ID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ranParameter-ID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RANFunctionDefinition_EventTrigger__ran_CallProcessTypes_List__Member__callProcessBreakpoints_List__Member__ran_CallProcessBreakpointParameters_List__Member, ranParameter_Name),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANParameter_Name,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ranParameter-Name"
		},
};
static const ber_tlv_tag_t asn_DEF_Member_tags_22[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Member_tag2el_22[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ranParameter-ID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* ranParameter-Name */
};
static asn_SEQUENCE_specifics_t asn_SPC_Member_specs_22 = {
	sizeof(struct RANFunctionDefinition_EventTrigger__ran_CallProcessTypes_List__Member__callProcessBreakpoints_List__Member__ran_CallProcessBreakpointParameters_List__Member),
	offsetof(struct RANFunctionDefinition_EventTrigger__ran_CallProcessTypes_List__Member__callProcessBreakpoints_List__Member__ran_CallProcessBreakpointParameters_List__Member, _asn_ctx),
	asn_MAP_Member_tag2el_22,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_Member_22 = {
	"SEQUENCE",
	"SEQUENCE",
	&asn_OP_SEQUENCE,
	asn_DEF_Member_tags_22,
	sizeof(asn_DEF_Member_tags_22)
		/sizeof(asn_DEF_Member_tags_22[0]), /* 1 */
	asn_DEF_Member_tags_22,	/* Same as above */
	sizeof(asn_DEF_Member_tags_22)
		/sizeof(asn_DEF_Member_tags_22[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Member_22,
	2,	/* Elements count */
	&asn_SPC_Member_specs_22	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ran_CallProcessBreakpointParameters_List_21[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Member_22,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ran_CallProcessBreakpointParameters_List_tags_21[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_ran_CallProcessBreakpointParameters_List_specs_21 = {
	sizeof(struct RANFunctionDefinition_EventTrigger__ran_CallProcessTypes_List__Member__callProcessBreakpoints_List__Member__ran_CallProcessBreakpointParameters_List),
	offsetof(struct RANFunctionDefinition_EventTrigger__ran_CallProcessTypes_List__Member__callProcessBreakpoints_List__Member__ran_CallProcessBreakpointParameters_List, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ran_CallProcessBreakpointParameters_List_21 = {
	"ran-CallProcessBreakpointParameters-List",
	"ran-CallProcessBreakpointParameters-List",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ran_CallProcessBreakpointParameters_List_tags_21,
	sizeof(asn_DEF_ran_CallProcessBreakpointParameters_List_tags_21)
		/sizeof(asn_DEF_ran_CallProcessBreakpointParameters_List_tags_21[0]) - 1, /* 1 */
	asn_DEF_ran_CallProcessBreakpointParameters_List_tags_21,	/* Same as above */
	sizeof(asn_DEF_ran_CallProcessBreakpointParameters_List_tags_21)
		/sizeof(asn_DEF_ran_CallProcessBreakpointParameters_List_tags_21[0]), /* 2 */
	{ &asn_OER_type_ran_CallProcessBreakpointParameters_List_constr_21, &asn_PER_type_ran_CallProcessBreakpointParameters_List_constr_21, SEQUENCE_OF_constraint },
	asn_MBR_ran_CallProcessBreakpointParameters_List_21,
	1,	/* Single element */
	&asn_SPC_ran_CallProcessBreakpointParameters_List_specs_21	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_Member_18[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RANFunctionDefinition_EventTrigger__ran_CallProcessTypes_List__Member__callProcessBreakpoints_List__Member, callProcessBreakpoint_ID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RIC_CallProcessBreakpoint_ID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"callProcessBreakpoint-ID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RANFunctionDefinition_EventTrigger__ran_CallProcessTypes_List__Member__callProcessBreakpoints_List__Member, callProcessBreakpoint_Name),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RIC_CallProcessBreakpoint_Name,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"callProcessBreakpoint-Name"
		},
	{ ATF_POINTER, 1, offsetof(struct RANFunctionDefinition_EventTrigger__ran_CallProcessTypes_List__Member__callProcessBreakpoints_List__Member, ran_CallProcessBreakpointParameters_List),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_ran_CallProcessBreakpointParameters_List_21,
		0,
		{ &asn_OER_memb_ran_CallProcessBreakpointParameters_List_constr_21, &asn_PER_memb_ran_CallProcessBreakpointParameters_List_constr_21,  memb_ran_CallProcessBreakpointParameters_List_constraint_18 },
		0, 0, /* No default value */
		"ran-CallProcessBreakpointParameters-List"
		},
};
static const int asn_MAP_Member_oms_18[] = { 2 };
static const ber_tlv_tag_t asn_DEF_Member_tags_18[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Member_tag2el_18[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* callProcessBreakpoint-ID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* callProcessBreakpoint-Name */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* ran-CallProcessBreakpointParameters-List */
};
static asn_SEQUENCE_specifics_t asn_SPC_Member_specs_18 = {
	sizeof(struct RANFunctionDefinition_EventTrigger__ran_CallProcessTypes_List__Member__callProcessBreakpoints_List__Member),
	offsetof(struct RANFunctionDefinition_EventTrigger__ran_CallProcessTypes_List__Member__callProcessBreakpoints_List__Member, _asn_ctx),
	asn_MAP_Member_tag2el_18,
	3,	/* Count of tags in the map */
	asn_MAP_Member_oms_18,	/* Optional members */
	1, 0,	/* Root/Additions */
	3,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_Member_18 = {
	"SEQUENCE",
	"SEQUENCE",
	&asn_OP_SEQUENCE,
	asn_DEF_Member_tags_18,
	sizeof(asn_DEF_Member_tags_18)
		/sizeof(asn_DEF_Member_tags_18[0]), /* 1 */
	asn_DEF_Member_tags_18,	/* Same as above */
	sizeof(asn_DEF_Member_tags_18)
		/sizeof(asn_DEF_Member_tags_18[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Member_18,
	3,	/* Elements count */
	&asn_SPC_Member_specs_18	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_callProcessBreakpoints_List_17[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Member_18,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_callProcessBreakpoints_List_tags_17[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_callProcessBreakpoints_List_specs_17 = {
	sizeof(struct RANFunctionDefinition_EventTrigger__ran_CallProcessTypes_List__Member__callProcessBreakpoints_List),
	offsetof(struct RANFunctionDefinition_EventTrigger__ran_CallProcessTypes_List__Member__callProcessBreakpoints_List, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_callProcessBreakpoints_List_17 = {
	"callProcessBreakpoints-List",
	"callProcessBreakpoints-List",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_callProcessBreakpoints_List_tags_17,
	sizeof(asn_DEF_callProcessBreakpoints_List_tags_17)
		/sizeof(asn_DEF_callProcessBreakpoints_List_tags_17[0]) - 1, /* 1 */
	asn_DEF_callProcessBreakpoints_List_tags_17,	/* Same as above */
	sizeof(asn_DEF_callProcessBreakpoints_List_tags_17)
		/sizeof(asn_DEF_callProcessBreakpoints_List_tags_17[0]), /* 2 */
	{ &asn_OER_type_callProcessBreakpoints_List_constr_17, &asn_PER_type_callProcessBreakpoints_List_constr_17, SEQUENCE_OF_constraint },
	asn_MBR_callProcessBreakpoints_List_17,
	1,	/* Single element */
	&asn_SPC_callProcessBreakpoints_List_specs_17	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_Member_14[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RANFunctionDefinition_EventTrigger__ran_CallProcessTypes_List__Member, callProcessType_ID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RIC_CallProcessType_ID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"callProcessType-ID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RANFunctionDefinition_EventTrigger__ran_CallProcessTypes_List__Member, callProcessType_Name),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RIC_CallProcessType_Name,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"callProcessType-Name"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RANFunctionDefinition_EventTrigger__ran_CallProcessTypes_List__Member, callProcessBreakpoints_List),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_callProcessBreakpoints_List_17,
		0,
		{ &asn_OER_memb_callProcessBreakpoints_List_constr_17, &asn_PER_memb_callProcessBreakpoints_List_constr_17,  memb_callProcessBreakpoints_List_constraint_14 },
		0, 0, /* No default value */
		"callProcessBreakpoints-List"
		},
};
static const ber_tlv_tag_t asn_DEF_Member_tags_14[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Member_tag2el_14[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* callProcessType-ID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* callProcessType-Name */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* callProcessBreakpoints-List */
};
static asn_SEQUENCE_specifics_t asn_SPC_Member_specs_14 = {
	sizeof(struct RANFunctionDefinition_EventTrigger__ran_CallProcessTypes_List__Member),
	offsetof(struct RANFunctionDefinition_EventTrigger__ran_CallProcessTypes_List__Member, _asn_ctx),
	asn_MAP_Member_tag2el_14,
	3,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	3,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_Member_14 = {
	"SEQUENCE",
	"SEQUENCE",
	&asn_OP_SEQUENCE,
	asn_DEF_Member_tags_14,
	sizeof(asn_DEF_Member_tags_14)
		/sizeof(asn_DEF_Member_tags_14[0]), /* 1 */
	asn_DEF_Member_tags_14,	/* Same as above */
	sizeof(asn_DEF_Member_tags_14)
		/sizeof(asn_DEF_Member_tags_14[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Member_14,
	3,	/* Elements count */
	&asn_SPC_Member_specs_14	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ran_CallProcessTypes_List_13[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Member_14,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ran_CallProcessTypes_List_tags_13[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_ran_CallProcessTypes_List_specs_13 = {
	sizeof(struct RANFunctionDefinition_EventTrigger__ran_CallProcessTypes_List),
	offsetof(struct RANFunctionDefinition_EventTrigger__ran_CallProcessTypes_List, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ran_CallProcessTypes_List_13 = {
	"ran-CallProcessTypes-List",
	"ran-CallProcessTypes-List",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ran_CallProcessTypes_List_tags_13,
	sizeof(asn_DEF_ran_CallProcessTypes_List_tags_13)
		/sizeof(asn_DEF_ran_CallProcessTypes_List_tags_13[0]) - 1, /* 1 */
	asn_DEF_ran_CallProcessTypes_List_tags_13,	/* Same as above */
	sizeof(asn_DEF_ran_CallProcessTypes_List_tags_13)
		/sizeof(asn_DEF_ran_CallProcessTypes_List_tags_13[0]), /* 2 */
	{ &asn_OER_type_ran_CallProcessTypes_List_constr_13, &asn_PER_type_ran_CallProcessTypes_List_constr_13, SEQUENCE_OF_constraint },
	asn_MBR_ran_CallProcessTypes_List_13,
	1,	/* Single element */
	&asn_SPC_ran_CallProcessTypes_List_specs_13	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_Member_29[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RANFunctionDefinition_EventTrigger__ran_UEIdentificationParameters_List__Member, ranParameter_ID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANParameter_ID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ranParameter-ID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RANFunctionDefinition_EventTrigger__ran_UEIdentificationParameters_List__Member, ranParameter_Name),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANParameter_Name,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ranParameter-Name"
		},
};
static const ber_tlv_tag_t asn_DEF_Member_tags_29[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Member_tag2el_29[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ranParameter-ID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* ranParameter-Name */
};
static asn_SEQUENCE_specifics_t asn_SPC_Member_specs_29 = {
	sizeof(struct RANFunctionDefinition_EventTrigger__ran_UEIdentificationParameters_List__Member),
	offsetof(struct RANFunctionDefinition_EventTrigger__ran_UEIdentificationParameters_List__Member, _asn_ctx),
	asn_MAP_Member_tag2el_29,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_Member_29 = {
	"SEQUENCE",
	"SEQUENCE",
	&asn_OP_SEQUENCE,
	asn_DEF_Member_tags_29,
	sizeof(asn_DEF_Member_tags_29)
		/sizeof(asn_DEF_Member_tags_29[0]), /* 1 */
	asn_DEF_Member_tags_29,	/* Same as above */
	sizeof(asn_DEF_Member_tags_29)
		/sizeof(asn_DEF_Member_tags_29[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Member_29,
	2,	/* Elements count */
	&asn_SPC_Member_specs_29	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ran_UEIdentificationParameters_List_28[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Member_29,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ran_UEIdentificationParameters_List_tags_28[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_ran_UEIdentificationParameters_List_specs_28 = {
	sizeof(struct RANFunctionDefinition_EventTrigger__ran_UEIdentificationParameters_List),
	offsetof(struct RANFunctionDefinition_EventTrigger__ran_UEIdentificationParameters_List, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ran_UEIdentificationParameters_List_28 = {
	"ran-UEIdentificationParameters-List",
	"ran-UEIdentificationParameters-List",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ran_UEIdentificationParameters_List_tags_28,
	sizeof(asn_DEF_ran_UEIdentificationParameters_List_tags_28)
		/sizeof(asn_DEF_ran_UEIdentificationParameters_List_tags_28[0]) - 1, /* 1 */
	asn_DEF_ran_UEIdentificationParameters_List_tags_28,	/* Same as above */
	sizeof(asn_DEF_ran_UEIdentificationParameters_List_tags_28)
		/sizeof(asn_DEF_ran_UEIdentificationParameters_List_tags_28[0]), /* 2 */
	{ &asn_OER_type_ran_UEIdentificationParameters_List_constr_28, &asn_PER_type_ran_UEIdentificationParameters_List_constr_28, SEQUENCE_OF_constraint },
	asn_MBR_ran_UEIdentificationParameters_List_28,
	1,	/* Single element */
	&asn_SPC_ran_UEIdentificationParameters_List_specs_28	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_Member_34[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RANFunctionDefinition_EventTrigger__ran_CellIdentificationParameters_List__Member, ranParameter_ID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANParameter_ID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ranParameter-ID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RANFunctionDefinition_EventTrigger__ran_CellIdentificationParameters_List__Member, ranParameter_Name),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANParameter_Name,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ranParameter-Name"
		},
};
static const ber_tlv_tag_t asn_DEF_Member_tags_34[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Member_tag2el_34[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ranParameter-ID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* ranParameter-Name */
};
static asn_SEQUENCE_specifics_t asn_SPC_Member_specs_34 = {
	sizeof(struct RANFunctionDefinition_EventTrigger__ran_CellIdentificationParameters_List__Member),
	offsetof(struct RANFunctionDefinition_EventTrigger__ran_CellIdentificationParameters_List__Member, _asn_ctx),
	asn_MAP_Member_tag2el_34,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_Member_34 = {
	"SEQUENCE",
	"SEQUENCE",
	&asn_OP_SEQUENCE,
	asn_DEF_Member_tags_34,
	sizeof(asn_DEF_Member_tags_34)
		/sizeof(asn_DEF_Member_tags_34[0]), /* 1 */
	asn_DEF_Member_tags_34,	/* Same as above */
	sizeof(asn_DEF_Member_tags_34)
		/sizeof(asn_DEF_Member_tags_34[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Member_34,
	2,	/* Elements count */
	&asn_SPC_Member_specs_34	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ran_CellIdentificationParameters_List_33[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Member_34,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ran_CellIdentificationParameters_List_tags_33[] = {
	(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_ran_CellIdentificationParameters_List_specs_33 = {
	sizeof(struct RANFunctionDefinition_EventTrigger__ran_CellIdentificationParameters_List),
	offsetof(struct RANFunctionDefinition_EventTrigger__ran_CellIdentificationParameters_List, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ran_CellIdentificationParameters_List_33 = {
	"ran-CellIdentificationParameters-List",
	"ran-CellIdentificationParameters-List",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ran_CellIdentificationParameters_List_tags_33,
	sizeof(asn_DEF_ran_CellIdentificationParameters_List_tags_33)
		/sizeof(asn_DEF_ran_CellIdentificationParameters_List_tags_33[0]) - 1, /* 1 */
	asn_DEF_ran_CellIdentificationParameters_List_tags_33,	/* Same as above */
	sizeof(asn_DEF_ran_CellIdentificationParameters_List_tags_33)
		/sizeof(asn_DEF_ran_CellIdentificationParameters_List_tags_33[0]), /* 2 */
	{ &asn_OER_type_ran_CellIdentificationParameters_List_constr_33, &asn_PER_type_ran_CellIdentificationParameters_List_constr_33, SEQUENCE_OF_constraint },
	asn_MBR_ran_CellIdentificationParameters_List_33,
	1,	/* Single element */
	&asn_SPC_ran_CellIdentificationParameters_List_specs_33	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_RANFunctionDefinition_EventTrigger_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RANFunctionDefinition_EventTrigger, ric_EventTriggerStyle_List),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_ric_EventTriggerStyle_List_2,
		0,
		{ &asn_OER_memb_ric_EventTriggerStyle_List_constr_2, &asn_PER_memb_ric_EventTriggerStyle_List_constr_2,  memb_ric_EventTriggerStyle_List_constraint_1 },
		0, 0, /* No default value */
		"ric-EventTriggerStyle-List"
		},
	{ ATF_POINTER, 4, offsetof(struct RANFunctionDefinition_EventTrigger, ran_L2Parameters_List),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		0,
		&asn_DEF_ran_L2Parameters_List_8,
		0,
		{ &asn_OER_memb_ran_L2Parameters_List_constr_8, &asn_PER_memb_ran_L2Parameters_List_constr_8,  memb_ran_L2Parameters_List_constraint_1 },
		0, 0, /* No default value */
		"ran-L2Parameters-List"
		},
	{ ATF_POINTER, 3, offsetof(struct RANFunctionDefinition_EventTrigger, ran_CallProcessTypes_List),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_ran_CallProcessTypes_List_13,
		0,
		{ &asn_OER_memb_ran_CallProcessTypes_List_constr_13, &asn_PER_memb_ran_CallProcessTypes_List_constr_13,  memb_ran_CallProcessTypes_List_constraint_1 },
		0, 0, /* No default value */
		"ran-CallProcessTypes-List"
		},
	{ ATF_POINTER, 2, offsetof(struct RANFunctionDefinition_EventTrigger, ran_UEIdentificationParameters_List),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		0,
		&asn_DEF_ran_UEIdentificationParameters_List_28,
		0,
		{ &asn_OER_memb_ran_UEIdentificationParameters_List_constr_28, &asn_PER_memb_ran_UEIdentificationParameters_List_constr_28,  memb_ran_UEIdentificationParameters_List_constraint_1 },
		0, 0, /* No default value */
		"ran-UEIdentificationParameters-List"
		},
	{ ATF_POINTER, 1, offsetof(struct RANFunctionDefinition_EventTrigger, ran_CellIdentificationParameters_List),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		0,
		&asn_DEF_ran_CellIdentificationParameters_List_33,
		0,
		{ &asn_OER_memb_ran_CellIdentificationParameters_List_constr_33, &asn_PER_memb_ran_CellIdentificationParameters_List_constr_33,  memb_ran_CellIdentificationParameters_List_constraint_1 },
		0, 0, /* No default value */
		"ran-CellIdentificationParameters-List"
		},
};
static const int asn_MAP_RANFunctionDefinition_EventTrigger_oms_1[] = { 1, 2, 3, 4 };
static const ber_tlv_tag_t asn_DEF_RANFunctionDefinition_EventTrigger_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RANFunctionDefinition_EventTrigger_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ric-EventTriggerStyle-List */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* ran-L2Parameters-List */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* ran-CallProcessTypes-List */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* ran-UEIdentificationParameters-List */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* ran-CellIdentificationParameters-List */
};
asn_SEQUENCE_specifics_t asn_SPC_RANFunctionDefinition_EventTrigger_specs_1 = {
	sizeof(struct RANFunctionDefinition_EventTrigger),
	offsetof(struct RANFunctionDefinition_EventTrigger, _asn_ctx),
	asn_MAP_RANFunctionDefinition_EventTrigger_tag2el_1,
	5,	/* Count of tags in the map */
	asn_MAP_RANFunctionDefinition_EventTrigger_oms_1,	/* Optional members */
	4, 0,	/* Root/Additions */
	5,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RANFunctionDefinition_EventTrigger = {
	"RANFunctionDefinition-EventTrigger",
	"RANFunctionDefinition-EventTrigger",
	&asn_OP_SEQUENCE,
	asn_DEF_RANFunctionDefinition_EventTrigger_tags_1,
	sizeof(asn_DEF_RANFunctionDefinition_EventTrigger_tags_1)
		/sizeof(asn_DEF_RANFunctionDefinition_EventTrigger_tags_1[0]), /* 1 */
	asn_DEF_RANFunctionDefinition_EventTrigger_tags_1,	/* Same as above */
	sizeof(asn_DEF_RANFunctionDefinition_EventTrigger_tags_1)
		/sizeof(asn_DEF_RANFunctionDefinition_EventTrigger_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_RANFunctionDefinition_EventTrigger_1,
	5,	/* Elements count */
	&asn_SPC_RANFunctionDefinition_EventTrigger_specs_1	/* Additional specs */
};

