/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-RC-IEs"
 * 	found in "rc.asn1"
 * 	`asn1c -pdu=auto -fno-include-deps -fcompound-names -findirect-choice -gen-PER -gen-OER`
 */

#include "RANFunctionDefinition-Insert.h"

static int
memb_ran_InsertIndicationParameters_List_constraint_9(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 65535)) {
		/* Perform validation of the inner elements */
		return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_ric_InsertIndication_List_constraint_3(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 65535)) {
		/* Perform validation of the inner elements */
		return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_ric_InsertStyle_List_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 63)) {
		/* Perform validation of the inner elements */
		return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_type_ran_InsertIndicationParameters_List_constr_12 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..65535)) */};
static asn_per_constraints_t asn_PER_type_ran_InsertIndicationParameters_List_constr_12 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_ran_InsertIndicationParameters_List_constr_12 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..65535)) */};
static asn_per_constraints_t asn_PER_memb_ran_InsertIndicationParameters_List_constr_12 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ric_InsertIndication_List_constr_8 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..65535)) */};
static asn_per_constraints_t asn_PER_type_ric_InsertIndication_List_constr_8 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_ric_InsertIndication_List_constr_8 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..65535)) */};
static asn_per_constraints_t asn_PER_memb_ric_InsertIndication_List_constr_8 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ric_InsertStyle_List_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..63)) */};
static asn_per_constraints_t asn_PER_type_ric_InsertStyle_List_constr_2 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 6,  6,  1,  63 }	/* (SIZE(1..63)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_ric_InsertStyle_List_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..63)) */};
static asn_per_constraints_t asn_PER_memb_ric_InsertStyle_List_constr_2 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 6,  6,  1,  63 }	/* (SIZE(1..63)) */,
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_Member_13[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RANFunctionDefinition_Insert__ric_InsertStyle_List__Member__ric_InsertIndication_List__Member__ran_InsertIndicationParameters_List__Member, ranParameter_ID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANParameter_ID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ranParameter-ID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RANFunctionDefinition_Insert__ric_InsertStyle_List__Member__ric_InsertIndication_List__Member__ran_InsertIndicationParameters_List__Member, ranParameter_Name),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANParameter_Name,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ranParameter-Name"
		},
};
static const ber_tlv_tag_t asn_DEF_Member_tags_13[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Member_tag2el_13[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ranParameter-ID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* ranParameter-Name */
};
static asn_SEQUENCE_specifics_t asn_SPC_Member_specs_13 = {
	sizeof(struct RANFunctionDefinition_Insert__ric_InsertStyle_List__Member__ric_InsertIndication_List__Member__ran_InsertIndicationParameters_List__Member),
	offsetof(struct RANFunctionDefinition_Insert__ric_InsertStyle_List__Member__ric_InsertIndication_List__Member__ran_InsertIndicationParameters_List__Member, _asn_ctx),
	asn_MAP_Member_tag2el_13,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_Member_13 = {
	"SEQUENCE",
	"SEQUENCE",
	&asn_OP_SEQUENCE,
	asn_DEF_Member_tags_13,
	sizeof(asn_DEF_Member_tags_13)
		/sizeof(asn_DEF_Member_tags_13[0]), /* 1 */
	asn_DEF_Member_tags_13,	/* Same as above */
	sizeof(asn_DEF_Member_tags_13)
		/sizeof(asn_DEF_Member_tags_13[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Member_13,
	2,	/* Elements count */
	&asn_SPC_Member_specs_13	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ran_InsertIndicationParameters_List_12[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Member_13,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ran_InsertIndicationParameters_List_tags_12[] = {
	(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_ran_InsertIndicationParameters_List_specs_12 = {
	sizeof(struct RANFunctionDefinition_Insert__ric_InsertStyle_List__Member__ric_InsertIndication_List__Member__ran_InsertIndicationParameters_List),
	offsetof(struct RANFunctionDefinition_Insert__ric_InsertStyle_List__Member__ric_InsertIndication_List__Member__ran_InsertIndicationParameters_List, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ran_InsertIndicationParameters_List_12 = {
	"ran-InsertIndicationParameters-List",
	"ran-InsertIndicationParameters-List",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ran_InsertIndicationParameters_List_tags_12,
	sizeof(asn_DEF_ran_InsertIndicationParameters_List_tags_12)
		/sizeof(asn_DEF_ran_InsertIndicationParameters_List_tags_12[0]) - 1, /* 1 */
	asn_DEF_ran_InsertIndicationParameters_List_tags_12,	/* Same as above */
	sizeof(asn_DEF_ran_InsertIndicationParameters_List_tags_12)
		/sizeof(asn_DEF_ran_InsertIndicationParameters_List_tags_12[0]), /* 2 */
	{ &asn_OER_type_ran_InsertIndicationParameters_List_constr_12, &asn_PER_type_ran_InsertIndicationParameters_List_constr_12, SEQUENCE_OF_constraint },
	asn_MBR_ran_InsertIndicationParameters_List_12,
	1,	/* Single element */
	&asn_SPC_ran_InsertIndicationParameters_List_specs_12	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_Member_9[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RANFunctionDefinition_Insert__ric_InsertStyle_List__Member__ric_InsertIndication_List__Member, ric_InsertIndication_ID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RIC_InsertIndication_ID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ric-InsertIndication-ID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RANFunctionDefinition_Insert__ric_InsertStyle_List__Member__ric_InsertIndication_List__Member, ric_InsertIndication_Name),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RIC_InsertIndication_Name,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ric-InsertIndication-Name"
		},
	{ ATF_POINTER, 1, offsetof(struct RANFunctionDefinition_Insert__ric_InsertStyle_List__Member__ric_InsertIndication_List__Member, ran_InsertIndicationParameters_List),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		0,
		&asn_DEF_ran_InsertIndicationParameters_List_12,
		0,
		{ &asn_OER_memb_ran_InsertIndicationParameters_List_constr_12, &asn_PER_memb_ran_InsertIndicationParameters_List_constr_12,  memb_ran_InsertIndicationParameters_List_constraint_9 },
		0, 0, /* No default value */
		"ran-InsertIndicationParameters-List"
		},
};
static const int asn_MAP_Member_oms_9[] = { 2 };
static const ber_tlv_tag_t asn_DEF_Member_tags_9[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Member_tag2el_9[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ric-InsertIndication-ID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* ric-InsertIndication-Name */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 } /* ran-InsertIndicationParameters-List */
};
static asn_SEQUENCE_specifics_t asn_SPC_Member_specs_9 = {
	sizeof(struct RANFunctionDefinition_Insert__ric_InsertStyle_List__Member__ric_InsertIndication_List__Member),
	offsetof(struct RANFunctionDefinition_Insert__ric_InsertStyle_List__Member__ric_InsertIndication_List__Member, _asn_ctx),
	asn_MAP_Member_tag2el_9,
	3,	/* Count of tags in the map */
	asn_MAP_Member_oms_9,	/* Optional members */
	1, 0,	/* Root/Additions */
	3,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_Member_9 = {
	"SEQUENCE",
	"SEQUENCE",
	&asn_OP_SEQUENCE,
	asn_DEF_Member_tags_9,
	sizeof(asn_DEF_Member_tags_9)
		/sizeof(asn_DEF_Member_tags_9[0]), /* 1 */
	asn_DEF_Member_tags_9,	/* Same as above */
	sizeof(asn_DEF_Member_tags_9)
		/sizeof(asn_DEF_Member_tags_9[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Member_9,
	3,	/* Elements count */
	&asn_SPC_Member_specs_9	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ric_InsertIndication_List_8[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Member_9,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ric_InsertIndication_List_tags_8[] = {
	(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_ric_InsertIndication_List_specs_8 = {
	sizeof(struct RANFunctionDefinition_Insert__ric_InsertStyle_List__Member__ric_InsertIndication_List),
	offsetof(struct RANFunctionDefinition_Insert__ric_InsertStyle_List__Member__ric_InsertIndication_List, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ric_InsertIndication_List_8 = {
	"ric-InsertIndication-List",
	"ric-InsertIndication-List",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ric_InsertIndication_List_tags_8,
	sizeof(asn_DEF_ric_InsertIndication_List_tags_8)
		/sizeof(asn_DEF_ric_InsertIndication_List_tags_8[0]) - 1, /* 1 */
	asn_DEF_ric_InsertIndication_List_tags_8,	/* Same as above */
	sizeof(asn_DEF_ric_InsertIndication_List_tags_8)
		/sizeof(asn_DEF_ric_InsertIndication_List_tags_8[0]), /* 2 */
	{ &asn_OER_type_ric_InsertIndication_List_constr_8, &asn_PER_type_ric_InsertIndication_List_constr_8, SEQUENCE_OF_constraint },
	asn_MBR_ric_InsertIndication_List_8,
	1,	/* Single element */
	&asn_SPC_ric_InsertIndication_List_specs_8	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_Member_3[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RANFunctionDefinition_Insert__ric_InsertStyle_List__Member, ric_InsertStyle_Type),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RIC_Style_Type,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ric-InsertStyle-Type"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RANFunctionDefinition_Insert__ric_InsertStyle_List__Member, ric_InsertStyle_Name),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RIC_Style_Name,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ric-InsertStyle-Name"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RANFunctionDefinition_Insert__ric_InsertStyle_List__Member, ric_SupportedEventTriggerStyle_Type),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RIC_Style_Type,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ric-SupportedEventTriggerStyle-Type"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RANFunctionDefinition_Insert__ric_InsertStyle_List__Member, ric_ActionDefinitionFormat_Type),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RIC_Format_Type,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ric-ActionDefinitionFormat-Type"
		},
	{ ATF_POINTER, 1, offsetof(struct RANFunctionDefinition_Insert__ric_InsertStyle_List__Member, ric_InsertIndication_List),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		0,
		&asn_DEF_ric_InsertIndication_List_8,
		0,
		{ &asn_OER_memb_ric_InsertIndication_List_constr_8, &asn_PER_memb_ric_InsertIndication_List_constr_8,  memb_ric_InsertIndication_List_constraint_3 },
		0, 0, /* No default value */
		"ric-InsertIndication-List"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RANFunctionDefinition_Insert__ric_InsertStyle_List__Member, ric_IndicationHeaderFormat_Type),
		(ASN_TAG_CLASS_CONTEXT | (5 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RIC_Format_Type,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ric-IndicationHeaderFormat-Type"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RANFunctionDefinition_Insert__ric_InsertStyle_List__Member, ric_IndicationMessageFormat_Type),
		(ASN_TAG_CLASS_CONTEXT | (6 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RIC_Format_Type,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ric-IndicationMessageFormat-Type"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RANFunctionDefinition_Insert__ric_InsertStyle_List__Member, ric_CallProcessIDFormat_Type),
		(ASN_TAG_CLASS_CONTEXT | (7 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RIC_Format_Type,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ric-CallProcessIDFormat-Type"
		},
};
static const int asn_MAP_Member_oms_3[] = { 4 };
static const ber_tlv_tag_t asn_DEF_Member_tags_3[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Member_tag2el_3[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ric-InsertStyle-Type */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* ric-InsertStyle-Name */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* ric-SupportedEventTriggerStyle-Type */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* ric-ActionDefinitionFormat-Type */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 }, /* ric-InsertIndication-List */
    { (ASN_TAG_CLASS_CONTEXT | (5 << 2)), 5, 0, 0 }, /* ric-IndicationHeaderFormat-Type */
    { (ASN_TAG_CLASS_CONTEXT | (6 << 2)), 6, 0, 0 }, /* ric-IndicationMessageFormat-Type */
    { (ASN_TAG_CLASS_CONTEXT | (7 << 2)), 7, 0, 0 } /* ric-CallProcessIDFormat-Type */
};
static asn_SEQUENCE_specifics_t asn_SPC_Member_specs_3 = {
	sizeof(struct RANFunctionDefinition_Insert__ric_InsertStyle_List__Member),
	offsetof(struct RANFunctionDefinition_Insert__ric_InsertStyle_List__Member, _asn_ctx),
	asn_MAP_Member_tag2el_3,
	8,	/* Count of tags in the map */
	asn_MAP_Member_oms_3,	/* Optional members */
	1, 0,	/* Root/Additions */
	8,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_Member_3 = {
	"SEQUENCE",
	"SEQUENCE",
	&asn_OP_SEQUENCE,
	asn_DEF_Member_tags_3,
	sizeof(asn_DEF_Member_tags_3)
		/sizeof(asn_DEF_Member_tags_3[0]), /* 1 */
	asn_DEF_Member_tags_3,	/* Same as above */
	sizeof(asn_DEF_Member_tags_3)
		/sizeof(asn_DEF_Member_tags_3[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Member_3,
	8,	/* Elements count */
	&asn_SPC_Member_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ric_InsertStyle_List_2[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Member_3,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ric_InsertStyle_List_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_ric_InsertStyle_List_specs_2 = {
	sizeof(struct RANFunctionDefinition_Insert__ric_InsertStyle_List),
	offsetof(struct RANFunctionDefinition_Insert__ric_InsertStyle_List, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ric_InsertStyle_List_2 = {
	"ric-InsertStyle-List",
	"ric-InsertStyle-List",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ric_InsertStyle_List_tags_2,
	sizeof(asn_DEF_ric_InsertStyle_List_tags_2)
		/sizeof(asn_DEF_ric_InsertStyle_List_tags_2[0]) - 1, /* 1 */
	asn_DEF_ric_InsertStyle_List_tags_2,	/* Same as above */
	sizeof(asn_DEF_ric_InsertStyle_List_tags_2)
		/sizeof(asn_DEF_ric_InsertStyle_List_tags_2[0]), /* 2 */
	{ &asn_OER_type_ric_InsertStyle_List_constr_2, &asn_PER_type_ric_InsertStyle_List_constr_2, SEQUENCE_OF_constraint },
	asn_MBR_ric_InsertStyle_List_2,
	1,	/* Single element */
	&asn_SPC_ric_InsertStyle_List_specs_2	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_RANFunctionDefinition_Insert_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RANFunctionDefinition_Insert, ric_InsertStyle_List),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_ric_InsertStyle_List_2,
		0,
		{ &asn_OER_memb_ric_InsertStyle_List_constr_2, &asn_PER_memb_ric_InsertStyle_List_constr_2,  memb_ric_InsertStyle_List_constraint_1 },
		0, 0, /* No default value */
		"ric-InsertStyle-List"
		},
};
static const ber_tlv_tag_t asn_DEF_RANFunctionDefinition_Insert_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RANFunctionDefinition_Insert_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* ric-InsertStyle-List */
};
asn_SEQUENCE_specifics_t asn_SPC_RANFunctionDefinition_Insert_specs_1 = {
	sizeof(struct RANFunctionDefinition_Insert),
	offsetof(struct RANFunctionDefinition_Insert, _asn_ctx),
	asn_MAP_RANFunctionDefinition_Insert_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RANFunctionDefinition_Insert = {
	"RANFunctionDefinition-Insert",
	"RANFunctionDefinition-Insert",
	&asn_OP_SEQUENCE,
	asn_DEF_RANFunctionDefinition_Insert_tags_1,
	sizeof(asn_DEF_RANFunctionDefinition_Insert_tags_1)
		/sizeof(asn_DEF_RANFunctionDefinition_Insert_tags_1[0]), /* 1 */
	asn_DEF_RANFunctionDefinition_Insert_tags_1,	/* Same as above */
	sizeof(asn_DEF_RANFunctionDefinition_Insert_tags_1)
		/sizeof(asn_DEF_RANFunctionDefinition_Insert_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_RANFunctionDefinition_Insert_1,
	1,	/* Elements count */
	&asn_SPC_RANFunctionDefinition_Insert_specs_1	/* Additional specs */
};

