/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-RC-IEs"
 * 	found in "rc.asn1"
 * 	`asn1c -pdu=auto -fno-include-deps -fcompound-names -findirect-choice -gen-PER -gen-OER`
 */

#include "RANFunctionDefinition-Policy.h"

static int
memb_ran_PolicyActionParameters_List_constraint_8(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 65535)) {
		/* Perform validation of the inner elements */
		return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_ran_PolicyConditionParameters_List_constraint_8(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 65535)) {
		/* Perform validation of the inner elements */
		return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_ric_PolicyAction_List_constraint_3(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 65535)) {
		/* Perform validation of the inner elements */
		return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static int
memb_ric_PolicyStyle_List_constraint_1(const asn_TYPE_descriptor_t *td, const void *sptr,
			asn_app_constraint_failed_f *ctfailcb, void *app_key) {
	size_t size;
	
	if(!sptr) {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: value not given (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
	
	/* Determine the number of elements */
	size = _A_CSEQUENCE_FROM_VOID(sptr)->count;
	
	if((size >= 1 && size <= 63)) {
		/* Perform validation of the inner elements */
		return td->encoding_constraints.general_constraints(td, sptr, ctfailcb, app_key);
	} else {
		ASN__CTFAIL(app_key, td, sptr,
			"%s: constraint failed (%s:%d)",
			td->name, __FILE__, __LINE__);
		return -1;
	}
}

static asn_oer_constraints_t asn_OER_type_ran_PolicyActionParameters_List_constr_12 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..65535)) */};
static asn_per_constraints_t asn_PER_type_ran_PolicyActionParameters_List_constr_12 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ran_PolicyConditionParameters_List_constr_17 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..65535)) */};
static asn_per_constraints_t asn_PER_type_ran_PolicyConditionParameters_List_constr_17 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_ran_PolicyActionParameters_List_constr_12 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..65535)) */};
static asn_per_constraints_t asn_PER_memb_ran_PolicyActionParameters_List_constr_12 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_ran_PolicyConditionParameters_List_constr_17 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..65535)) */};
static asn_per_constraints_t asn_PER_memb_ran_PolicyConditionParameters_List_constr_17 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ric_PolicyAction_List_constr_7 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..65535)) */};
static asn_per_constraints_t asn_PER_type_ric_PolicyAction_List_constr_7 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_ric_PolicyAction_List_constr_7 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..65535)) */};
static asn_per_constraints_t asn_PER_memb_ric_PolicyAction_List_constr_7 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 16,  16,  1,  65535 }	/* (SIZE(1..65535)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_type_ric_PolicyStyle_List_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..63)) */};
static asn_per_constraints_t asn_PER_type_ric_PolicyStyle_List_constr_2 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 6,  6,  1,  63 }	/* (SIZE(1..63)) */,
	0, 0	/* No PER value map */
};
static asn_oer_constraints_t asn_OER_memb_ric_PolicyStyle_List_constr_2 CC_NOTUSED = {
	{ 0, 0 },
	-1	/* (SIZE(1..63)) */};
static asn_per_constraints_t asn_PER_memb_ric_PolicyStyle_List_constr_2 CC_NOTUSED = {
	{ APC_UNCONSTRAINED,	-1, -1,  0,  0 },
	{ APC_CONSTRAINED,	 6,  6,  1,  63 }	/* (SIZE(1..63)) */,
	0, 0	/* No PER value map */
};
static asn_TYPE_member_t asn_MBR_Member_13[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RANFunctionDefinition_Policy__ric_PolicyStyle_List__Member__ric_PolicyAction_List__Member__ran_PolicyActionParameters_List__Member, ranParameter_ID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANParameter_ID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ranParameter-ID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RANFunctionDefinition_Policy__ric_PolicyStyle_List__Member__ric_PolicyAction_List__Member__ran_PolicyActionParameters_List__Member, ranParameter_Name),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANParameter_Name,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ranParameter-Name"
		},
};
static const ber_tlv_tag_t asn_DEF_Member_tags_13[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Member_tag2el_13[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ranParameter-ID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* ranParameter-Name */
};
static asn_SEQUENCE_specifics_t asn_SPC_Member_specs_13 = {
	sizeof(struct RANFunctionDefinition_Policy__ric_PolicyStyle_List__Member__ric_PolicyAction_List__Member__ran_PolicyActionParameters_List__Member),
	offsetof(struct RANFunctionDefinition_Policy__ric_PolicyStyle_List__Member__ric_PolicyAction_List__Member__ran_PolicyActionParameters_List__Member, _asn_ctx),
	asn_MAP_Member_tag2el_13,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_Member_13 = {
	"SEQUENCE",
	"SEQUENCE",
	&asn_OP_SEQUENCE,
	asn_DEF_Member_tags_13,
	sizeof(asn_DEF_Member_tags_13)
		/sizeof(asn_DEF_Member_tags_13[0]), /* 1 */
	asn_DEF_Member_tags_13,	/* Same as above */
	sizeof(asn_DEF_Member_tags_13)
		/sizeof(asn_DEF_Member_tags_13[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Member_13,
	2,	/* Elements count */
	&asn_SPC_Member_specs_13	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ran_PolicyActionParameters_List_12[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Member_13,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ran_PolicyActionParameters_List_tags_12[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_ran_PolicyActionParameters_List_specs_12 = {
	sizeof(struct RANFunctionDefinition_Policy__ric_PolicyStyle_List__Member__ric_PolicyAction_List__Member__ran_PolicyActionParameters_List),
	offsetof(struct RANFunctionDefinition_Policy__ric_PolicyStyle_List__Member__ric_PolicyAction_List__Member__ran_PolicyActionParameters_List, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ran_PolicyActionParameters_List_12 = {
	"ran-PolicyActionParameters-List",
	"ran-PolicyActionParameters-List",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ran_PolicyActionParameters_List_tags_12,
	sizeof(asn_DEF_ran_PolicyActionParameters_List_tags_12)
		/sizeof(asn_DEF_ran_PolicyActionParameters_List_tags_12[0]) - 1, /* 1 */
	asn_DEF_ran_PolicyActionParameters_List_tags_12,	/* Same as above */
	sizeof(asn_DEF_ran_PolicyActionParameters_List_tags_12)
		/sizeof(asn_DEF_ran_PolicyActionParameters_List_tags_12[0]), /* 2 */
	{ &asn_OER_type_ran_PolicyActionParameters_List_constr_12, &asn_PER_type_ran_PolicyActionParameters_List_constr_12, SEQUENCE_OF_constraint },
	asn_MBR_ran_PolicyActionParameters_List_12,
	1,	/* Single element */
	&asn_SPC_ran_PolicyActionParameters_List_specs_12	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_Member_18[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RANFunctionDefinition_Policy__ric_PolicyStyle_List__Member__ric_PolicyAction_List__Member__ran_PolicyConditionParameters_List__Member, ranParameter_ID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANParameter_ID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ranParameter-ID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RANFunctionDefinition_Policy__ric_PolicyStyle_List__Member__ric_PolicyAction_List__Member__ran_PolicyConditionParameters_List__Member, ranParameter_Name),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RANParameter_Name,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ranParameter-Name"
		},
};
static const ber_tlv_tag_t asn_DEF_Member_tags_18[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Member_tag2el_18[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ranParameter-ID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 } /* ranParameter-Name */
};
static asn_SEQUENCE_specifics_t asn_SPC_Member_specs_18 = {
	sizeof(struct RANFunctionDefinition_Policy__ric_PolicyStyle_List__Member__ric_PolicyAction_List__Member__ran_PolicyConditionParameters_List__Member),
	offsetof(struct RANFunctionDefinition_Policy__ric_PolicyStyle_List__Member__ric_PolicyAction_List__Member__ran_PolicyConditionParameters_List__Member, _asn_ctx),
	asn_MAP_Member_tag2el_18,
	2,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	2,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_Member_18 = {
	"SEQUENCE",
	"SEQUENCE",
	&asn_OP_SEQUENCE,
	asn_DEF_Member_tags_18,
	sizeof(asn_DEF_Member_tags_18)
		/sizeof(asn_DEF_Member_tags_18[0]), /* 1 */
	asn_DEF_Member_tags_18,	/* Same as above */
	sizeof(asn_DEF_Member_tags_18)
		/sizeof(asn_DEF_Member_tags_18[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Member_18,
	2,	/* Elements count */
	&asn_SPC_Member_specs_18	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ran_PolicyConditionParameters_List_17[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Member_18,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ran_PolicyConditionParameters_List_tags_17[] = {
	(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_ran_PolicyConditionParameters_List_specs_17 = {
	sizeof(struct RANFunctionDefinition_Policy__ric_PolicyStyle_List__Member__ric_PolicyAction_List__Member__ran_PolicyConditionParameters_List),
	offsetof(struct RANFunctionDefinition_Policy__ric_PolicyStyle_List__Member__ric_PolicyAction_List__Member__ran_PolicyConditionParameters_List, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ran_PolicyConditionParameters_List_17 = {
	"ran-PolicyConditionParameters-List",
	"ran-PolicyConditionParameters-List",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ran_PolicyConditionParameters_List_tags_17,
	sizeof(asn_DEF_ran_PolicyConditionParameters_List_tags_17)
		/sizeof(asn_DEF_ran_PolicyConditionParameters_List_tags_17[0]) - 1, /* 1 */
	asn_DEF_ran_PolicyConditionParameters_List_tags_17,	/* Same as above */
	sizeof(asn_DEF_ran_PolicyConditionParameters_List_tags_17)
		/sizeof(asn_DEF_ran_PolicyConditionParameters_List_tags_17[0]), /* 2 */
	{ &asn_OER_type_ran_PolicyConditionParameters_List_constr_17, &asn_PER_type_ran_PolicyConditionParameters_List_constr_17, SEQUENCE_OF_constraint },
	asn_MBR_ran_PolicyConditionParameters_List_17,
	1,	/* Single element */
	&asn_SPC_ran_PolicyConditionParameters_List_specs_17	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_Member_8[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RANFunctionDefinition_Policy__ric_PolicyStyle_List__Member__ric_PolicyAction_List__Member, ric_PolicyAction_ID),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RIC_ControlAction_ID,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ric-PolicyAction-ID"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RANFunctionDefinition_Policy__ric_PolicyStyle_List__Member__ric_PolicyAction_List__Member, ric_PolicyAction_Name),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RIC_ControlAction_Name,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ric-PolicyAction-Name"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RANFunctionDefinition_Policy__ric_PolicyStyle_List__Member__ric_PolicyAction_List__Member, ric_ActionDefinitionFormat_Type),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RIC_Format_Type,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ric-ActionDefinitionFormat-Type"
		},
	{ ATF_POINTER, 2, offsetof(struct RANFunctionDefinition_Policy__ric_PolicyStyle_List__Member__ric_PolicyAction_List__Member, ran_PolicyActionParameters_List),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		0,
		&asn_DEF_ran_PolicyActionParameters_List_12,
		0,
		{ &asn_OER_memb_ran_PolicyActionParameters_List_constr_12, &asn_PER_memb_ran_PolicyActionParameters_List_constr_12,  memb_ran_PolicyActionParameters_List_constraint_8 },
		0, 0, /* No default value */
		"ran-PolicyActionParameters-List"
		},
	{ ATF_POINTER, 1, offsetof(struct RANFunctionDefinition_Policy__ric_PolicyStyle_List__Member__ric_PolicyAction_List__Member, ran_PolicyConditionParameters_List),
		(ASN_TAG_CLASS_CONTEXT | (4 << 2)),
		0,
		&asn_DEF_ran_PolicyConditionParameters_List_17,
		0,
		{ &asn_OER_memb_ran_PolicyConditionParameters_List_constr_17, &asn_PER_memb_ran_PolicyConditionParameters_List_constr_17,  memb_ran_PolicyConditionParameters_List_constraint_8 },
		0, 0, /* No default value */
		"ran-PolicyConditionParameters-List"
		},
};
static const int asn_MAP_Member_oms_8[] = { 3, 4 };
static const ber_tlv_tag_t asn_DEF_Member_tags_8[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Member_tag2el_8[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ric-PolicyAction-ID */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* ric-PolicyAction-Name */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* ric-ActionDefinitionFormat-Type */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 }, /* ran-PolicyActionParameters-List */
    { (ASN_TAG_CLASS_CONTEXT | (4 << 2)), 4, 0, 0 } /* ran-PolicyConditionParameters-List */
};
static asn_SEQUENCE_specifics_t asn_SPC_Member_specs_8 = {
	sizeof(struct RANFunctionDefinition_Policy__ric_PolicyStyle_List__Member__ric_PolicyAction_List__Member),
	offsetof(struct RANFunctionDefinition_Policy__ric_PolicyStyle_List__Member__ric_PolicyAction_List__Member, _asn_ctx),
	asn_MAP_Member_tag2el_8,
	5,	/* Count of tags in the map */
	asn_MAP_Member_oms_8,	/* Optional members */
	2, 0,	/* Root/Additions */
	5,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_Member_8 = {
	"SEQUENCE",
	"SEQUENCE",
	&asn_OP_SEQUENCE,
	asn_DEF_Member_tags_8,
	sizeof(asn_DEF_Member_tags_8)
		/sizeof(asn_DEF_Member_tags_8[0]), /* 1 */
	asn_DEF_Member_tags_8,	/* Same as above */
	sizeof(asn_DEF_Member_tags_8)
		/sizeof(asn_DEF_Member_tags_8[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Member_8,
	5,	/* Elements count */
	&asn_SPC_Member_specs_8	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ric_PolicyAction_List_7[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Member_8,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ric_PolicyAction_List_tags_7[] = {
	(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_ric_PolicyAction_List_specs_7 = {
	sizeof(struct RANFunctionDefinition_Policy__ric_PolicyStyle_List__Member__ric_PolicyAction_List),
	offsetof(struct RANFunctionDefinition_Policy__ric_PolicyStyle_List__Member__ric_PolicyAction_List, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ric_PolicyAction_List_7 = {
	"ric-PolicyAction-List",
	"ric-PolicyAction-List",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ric_PolicyAction_List_tags_7,
	sizeof(asn_DEF_ric_PolicyAction_List_tags_7)
		/sizeof(asn_DEF_ric_PolicyAction_List_tags_7[0]) - 1, /* 1 */
	asn_DEF_ric_PolicyAction_List_tags_7,	/* Same as above */
	sizeof(asn_DEF_ric_PolicyAction_List_tags_7)
		/sizeof(asn_DEF_ric_PolicyAction_List_tags_7[0]), /* 2 */
	{ &asn_OER_type_ric_PolicyAction_List_constr_7, &asn_PER_type_ric_PolicyAction_List_constr_7, SEQUENCE_OF_constraint },
	asn_MBR_ric_PolicyAction_List_7,
	1,	/* Single element */
	&asn_SPC_ric_PolicyAction_List_specs_7	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_Member_3[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RANFunctionDefinition_Policy__ric_PolicyStyle_List__Member, ric_PolicyStyle_Type),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RIC_Style_Type,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ric-PolicyStyle-Type"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RANFunctionDefinition_Policy__ric_PolicyStyle_List__Member, ric_PolicyStyle_Name),
		(ASN_TAG_CLASS_CONTEXT | (1 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RIC_Style_Name,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ric-PolicyStyle-Name"
		},
	{ ATF_NOFLAGS, 0, offsetof(struct RANFunctionDefinition_Policy__ric_PolicyStyle_List__Member, ric_SupportedEventTriggerStyle_Type),
		(ASN_TAG_CLASS_CONTEXT | (2 << 2)),
		-1,	/* IMPLICIT tag at current level */
		&asn_DEF_RIC_Style_Type,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		"ric-SupportedEventTriggerStyle-Type"
		},
	{ ATF_POINTER, 1, offsetof(struct RANFunctionDefinition_Policy__ric_PolicyStyle_List__Member, ric_PolicyAction_List),
		(ASN_TAG_CLASS_CONTEXT | (3 << 2)),
		0,
		&asn_DEF_ric_PolicyAction_List_7,
		0,
		{ &asn_OER_memb_ric_PolicyAction_List_constr_7, &asn_PER_memb_ric_PolicyAction_List_constr_7,  memb_ric_PolicyAction_List_constraint_3 },
		0, 0, /* No default value */
		"ric-PolicyAction-List"
		},
};
static const int asn_MAP_Member_oms_3[] = { 3 };
static const ber_tlv_tag_t asn_DEF_Member_tags_3[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_Member_tag2el_3[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 }, /* ric-PolicyStyle-Type */
    { (ASN_TAG_CLASS_CONTEXT | (1 << 2)), 1, 0, 0 }, /* ric-PolicyStyle-Name */
    { (ASN_TAG_CLASS_CONTEXT | (2 << 2)), 2, 0, 0 }, /* ric-SupportedEventTriggerStyle-Type */
    { (ASN_TAG_CLASS_CONTEXT | (3 << 2)), 3, 0, 0 } /* ric-PolicyAction-List */
};
static asn_SEQUENCE_specifics_t asn_SPC_Member_specs_3 = {
	sizeof(struct RANFunctionDefinition_Policy__ric_PolicyStyle_List__Member),
	offsetof(struct RANFunctionDefinition_Policy__ric_PolicyStyle_List__Member, _asn_ctx),
	asn_MAP_Member_tag2el_3,
	4,	/* Count of tags in the map */
	asn_MAP_Member_oms_3,	/* Optional members */
	1, 0,	/* Root/Additions */
	4,	/* First extension addition */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_Member_3 = {
	"SEQUENCE",
	"SEQUENCE",
	&asn_OP_SEQUENCE,
	asn_DEF_Member_tags_3,
	sizeof(asn_DEF_Member_tags_3)
		/sizeof(asn_DEF_Member_tags_3[0]), /* 1 */
	asn_DEF_Member_tags_3,	/* Same as above */
	sizeof(asn_DEF_Member_tags_3)
		/sizeof(asn_DEF_Member_tags_3[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_Member_3,
	4,	/* Elements count */
	&asn_SPC_Member_specs_3	/* Additional specs */
};

static asn_TYPE_member_t asn_MBR_ric_PolicyStyle_List_2[] = {
	{ ATF_POINTER, 0, 0,
		(ASN_TAG_CLASS_UNIVERSAL | (16 << 2)),
		0,
		&asn_DEF_Member_3,
		0,
		{ 0, 0, 0 },
		0, 0, /* No default value */
		""
		},
};
static const ber_tlv_tag_t asn_DEF_ric_PolicyStyle_List_tags_2[] = {
	(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static asn_SET_OF_specifics_t asn_SPC_ric_PolicyStyle_List_specs_2 = {
	sizeof(struct RANFunctionDefinition_Policy__ric_PolicyStyle_List),
	offsetof(struct RANFunctionDefinition_Policy__ric_PolicyStyle_List, _asn_ctx),
	0,	/* XER encoding is XMLDelimitedItemList */
};
static /* Use -fall-defs-global to expose */
asn_TYPE_descriptor_t asn_DEF_ric_PolicyStyle_List_2 = {
	"ric-PolicyStyle-List",
	"ric-PolicyStyle-List",
	&asn_OP_SEQUENCE_OF,
	asn_DEF_ric_PolicyStyle_List_tags_2,
	sizeof(asn_DEF_ric_PolicyStyle_List_tags_2)
		/sizeof(asn_DEF_ric_PolicyStyle_List_tags_2[0]) - 1, /* 1 */
	asn_DEF_ric_PolicyStyle_List_tags_2,	/* Same as above */
	sizeof(asn_DEF_ric_PolicyStyle_List_tags_2)
		/sizeof(asn_DEF_ric_PolicyStyle_List_tags_2[0]), /* 2 */
	{ &asn_OER_type_ric_PolicyStyle_List_constr_2, &asn_PER_type_ric_PolicyStyle_List_constr_2, SEQUENCE_OF_constraint },
	asn_MBR_ric_PolicyStyle_List_2,
	1,	/* Single element */
	&asn_SPC_ric_PolicyStyle_List_specs_2	/* Additional specs */
};

asn_TYPE_member_t asn_MBR_RANFunctionDefinition_Policy_1[] = {
	{ ATF_NOFLAGS, 0, offsetof(struct RANFunctionDefinition_Policy, ric_PolicyStyle_List),
		(ASN_TAG_CLASS_CONTEXT | (0 << 2)),
		0,
		&asn_DEF_ric_PolicyStyle_List_2,
		0,
		{ &asn_OER_memb_ric_PolicyStyle_List_constr_2, &asn_PER_memb_ric_PolicyStyle_List_constr_2,  memb_ric_PolicyStyle_List_constraint_1 },
		0, 0, /* No default value */
		"ric-PolicyStyle-List"
		},
};
static const ber_tlv_tag_t asn_DEF_RANFunctionDefinition_Policy_tags_1[] = {
	(ASN_TAG_CLASS_UNIVERSAL | (16 << 2))
};
static const asn_TYPE_tag2member_t asn_MAP_RANFunctionDefinition_Policy_tag2el_1[] = {
    { (ASN_TAG_CLASS_CONTEXT | (0 << 2)), 0, 0, 0 } /* ric-PolicyStyle-List */
};
asn_SEQUENCE_specifics_t asn_SPC_RANFunctionDefinition_Policy_specs_1 = {
	sizeof(struct RANFunctionDefinition_Policy),
	offsetof(struct RANFunctionDefinition_Policy, _asn_ctx),
	asn_MAP_RANFunctionDefinition_Policy_tag2el_1,
	1,	/* Count of tags in the map */
	0, 0, 0,	/* Optional elements (not needed) */
	1,	/* First extension addition */
};
asn_TYPE_descriptor_t asn_DEF_RANFunctionDefinition_Policy = {
	"RANFunctionDefinition-Policy",
	"RANFunctionDefinition-Policy",
	&asn_OP_SEQUENCE,
	asn_DEF_RANFunctionDefinition_Policy_tags_1,
	sizeof(asn_DEF_RANFunctionDefinition_Policy_tags_1)
		/sizeof(asn_DEF_RANFunctionDefinition_Policy_tags_1[0]), /* 1 */
	asn_DEF_RANFunctionDefinition_Policy_tags_1,	/* Same as above */
	sizeof(asn_DEF_RANFunctionDefinition_Policy_tags_1)
		/sizeof(asn_DEF_RANFunctionDefinition_Policy_tags_1[0]), /* 1 */
	{ 0, 0, SEQUENCE_constraint },
	asn_MBR_RANFunctionDefinition_Policy_1,
	1,	/* Elements count */
	&asn_SPC_RANFunctionDefinition_Policy_specs_1	/* Additional specs */
};

