/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-RC-IEs"
 * 	found in "f.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -pdu=auto -gen-PER -gen-OER -no-gen-example`
 */

#ifndef	_RANFunctionDefinition_Control_H_
#define	_RANFunctionDefinition_Control_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include "RIC-Style-Type.h"
#include "RIC-Style-Name.h"
#include "RIC-Format-Type.h"
#include "RIC-ControlAction-ID.h"
#include "RIC-ControlAction-Name.h"
#include "RANParameter-ID.h"
#include "RANParameter-Name.h"
#include <constr_SEQUENCE.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward definitions */
typedef struct RANFunctionDefinition_Control__ric_ControlStyle_List__Member__ric_ControlAction_List__Member__ran_ControlActionParameters_List__Member {
	RANParameter_ID_t	 ranParameter_ID;
	RANParameter_Name_t	 ranParameter_Name;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RANFunctionDefinition_Control__ric_ControlStyle_List__Member__ric_ControlAction_List__Member__ran_ControlActionParameters_List__Member;
typedef struct RANFunctionDefinition_Control__ric_ControlStyle_List__Member__ric_ControlAction_List__Member {
	RIC_ControlAction_ID_t	 ric_ControlAction_ID;
	RIC_ControlAction_Name_t	 ric_ControlAction_Name;
	struct RANFunctionDefinition_Control__ric_ControlStyle_List__Member__ric_ControlAction_List__Member__ran_ControlActionParameters_List {
		A_SEQUENCE_OF(RANFunctionDefinition_Control__ric_ControlStyle_List__Member__ric_ControlAction_List__Member__ran_ControlActionParameters_List__Member) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ran_ControlActionParameters_List;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RANFunctionDefinition_Control__ric_ControlStyle_List__Member__ric_ControlAction_List__Member;
typedef struct RANFunctionDefinition_Control__ric_ControlStyle_List__Member__ran_ControlOutcomeParameters_List__Member {
	RANParameter_ID_t	 ranParameter_ID;
	RANParameter_Name_t	 ranParameter_Name;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RANFunctionDefinition_Control__ric_ControlStyle_List__Member__ran_ControlOutcomeParameters_List__Member;
typedef struct RANFunctionDefinition_Control__ric_ControlStyle_List__Member {
	RIC_Style_Type_t	 ric_ControlStyle_Type;
	RIC_Style_Name_t	 ric_ControlStyle_Name;
	struct RANFunctionDefinition_Control__ric_ControlStyle_List__Member__ric_ControlAction_List {
		A_SEQUENCE_OF(RANFunctionDefinition_Control__ric_ControlStyle_List__Member__ric_ControlAction_List__Member) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ric_ControlAction_List;
	RIC_Format_Type_t	 ric_ControlHeaderFormat_Type;
	RIC_Format_Type_t	 ric_ControlMessageFormat_Type;
	RIC_Format_Type_t	*ric_CallProcessIDFormat_Type	/* OPTIONAL */;
	RIC_Format_Type_t	 ric_ControlOutcomeFormat_Type;
	struct RANFunctionDefinition_Control__ric_ControlStyle_List__Member__ran_ControlOutcomeParameters_List {
		A_SEQUENCE_OF(RANFunctionDefinition_Control__ric_ControlStyle_List__Member__ran_ControlOutcomeParameters_List__Member) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ran_ControlOutcomeParameters_List;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RANFunctionDefinition_Control__ric_ControlStyle_List__Member;

/* RANFunctionDefinition-Control */
typedef struct RANFunctionDefinition_Control {
	struct RANFunctionDefinition_Control__ric_ControlStyle_List {
		A_SEQUENCE_OF(RANFunctionDefinition_Control__ric_ControlStyle_List__Member) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} ric_ControlStyle_List;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RANFunctionDefinition_Control_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RANFunctionDefinition_Control;
extern asn_SEQUENCE_specifics_t asn_SPC_RANFunctionDefinition_Control_specs_1;
extern asn_TYPE_member_t asn_MBR_RANFunctionDefinition_Control_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _RANFunctionDefinition_Control_H_ */
#include <asn_internal.h>
