/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-RC-IEs"
 * 	found in "f.asn"
 * 	`asn1c -fcompound-names -fno-include-deps -findirect-choice -pdu=auto -gen-PER -gen-OER -no-gen-example`
 */

#ifndef	_RANFunctionDefinition_Policy_H_
#define	_RANFunctionDefinition_Policy_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include "RIC-Style-Type.h"
#include "RIC-Style-Name.h"
#include "RIC-ControlAction-ID.h"
#include "RIC-ControlAction-Name.h"
#include "RIC-Format-Type.h"
#include "RANParameter-ID.h"
#include "RANParameter-Name.h"
#include <constr_SEQUENCE.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward definitions */
typedef struct RANFunctionDefinition_Policy__ric_PolicyStyle_List__Member__ric_PolicyAction_List__Member__ran_PolicyActionParameters_List__Member {
	RANParameter_ID_t	 ranParameter_ID;
	RANParameter_Name_t	 ranParameter_Name;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RANFunctionDefinition_Policy__ric_PolicyStyle_List__Member__ric_PolicyAction_List__Member__ran_PolicyActionParameters_List__Member;

typedef struct RANFunctionDefinition_Policy__ric_PolicyStyle_List__Member__ric_PolicyAction_List__Member__ran_PolicyConditionParameters_List__Member {
	RANParameter_ID_t	 ranParameter_ID;
	RANParameter_Name_t	 ranParameter_Name;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RANFunctionDefinition_Policy__ric_PolicyStyle_List__Member__ric_PolicyAction_List__Member__ran_PolicyConditionParameters_List__Member;

typedef struct RANFunctionDefinition_Policy__ric_PolicyStyle_List__Member__ric_PolicyAction_List__Member {
	RIC_ControlAction_ID_t	 ric_PolicyAction_ID;
	RIC_ControlAction_Name_t	 ric_PolicyAction_Name;
	RIC_Format_Type_t	 ric_ActionDefinitionFormat_Type;
	struct RANFunctionDefinition_Policy__ric_PolicyStyle_List__Member__ric_PolicyAction_List__Member__ran_PolicyActionParameters_List {
		A_SEQUENCE_OF(RANFunctionDefinition_Policy__ric_PolicyStyle_List__Member__ric_PolicyAction_List__Member__ran_PolicyActionParameters_List__Member) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ran_PolicyActionParameters_List;
	struct RANFunctionDefinition_Policy__ric_PolicyStyle_List__Member__ric_PolicyAction_List__Member__ran_PolicyConditionParameters_List {
		A_SEQUENCE_OF(RANFunctionDefinition_Policy__ric_PolicyStyle_List__Member__ric_PolicyAction_List__Member__ran_PolicyConditionParameters_List__Member) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ran_PolicyConditionParameters_List;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RANFunctionDefinition_Policy__ric_PolicyStyle_List__Member__ric_PolicyAction_List__Member;

typedef struct RANFunctionDefinition_Policy__ric_PolicyStyle_List__Member {
	RIC_Style_Type_t	 ric_PolicyStyle_Type;
	RIC_Style_Name_t	 ric_PolicyStyle_Name;
	RIC_Style_Type_t	 ric_SupportedEventTriggerStyle_Type;
	struct RANFunctionDefinition_Policy__ric_PolicyStyle_List__Member__ric_PolicyAction_List {
		A_SEQUENCE_OF(RANFunctionDefinition_Policy__ric_PolicyStyle_List__Member__ric_PolicyAction_List__Member) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ric_PolicyAction_List;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RANFunctionDefinition_Policy__ric_PolicyStyle_List__Member;

/* RANFunctionDefinition-Policy */
typedef struct RANFunctionDefinition_Policy {
	struct RANFunctionDefinition_Policy__ric_PolicyStyle_List {
		A_SEQUENCE_OF(RANFunctionDefinition_Policy__ric_PolicyStyle_List__Member) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} ric_PolicyStyle_List;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RANFunctionDefinition_Policy_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RANFunctionDefinition_Policy;
extern asn_SEQUENCE_specifics_t asn_SPC_RANFunctionDefinition_Policy_specs_1;
extern asn_TYPE_member_t asn_MBR_RANFunctionDefinition_Policy_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _RANFunctionDefinition_Policy_H_ */
#include <asn_internal.h>
