/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-RC-IEs"
 * 	found in "rc.asn1"
 * 	`asn1c -pdu=auto -fno-include-deps -fcompound-names -findirect-choice -gen-PER -gen-OER`
 */

#ifndef	_RANParameter_STRUCTURE_H_
#define	_RANParameter_STRUCTURE_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include "RANParameter-ID.h"
#include <constr_SEQUENCE.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward declarations */
struct RANParameter_ValueType;

/* Forward definitions */
typedef struct RANParameter_STRUCTURE__sequence_of_ranParameters__Member {
	RANParameter_ID_t	 ranParameter_ID;
	struct RANParameter_ValueType	*ranParameter_valueType;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RANParameter_STRUCTURE__sequence_of_ranParameters__Member;

/* RANParameter-STRUCTURE */
typedef struct RANParameter_STRUCTURE {
	struct RANParameter_STRUCTURE__sequence_of_ranParameters {
		A_SEQUENCE_OF(RANParameter_STRUCTURE__sequence_of_ranParameters__Member) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *sequence_of_ranParameters;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RANParameter_STRUCTURE_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RANParameter_STRUCTURE;
extern asn_SEQUENCE_specifics_t asn_SPC_RANParameter_STRUCTURE_specs_1;
extern asn_TYPE_member_t asn_MBR_RANParameter_STRUCTURE_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _RANParameter_STRUCTURE_H_ */
#include <asn_internal.h>
