/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-RC-IEs"
 * 	found in "rc.asn1"
 * 	`asn1c -pdu=auto -fno-include-deps -fcompound-names -findirect-choice -gen-PER -gen-OER`
 */

#ifndef	_RANFunctionDefinition_Report_H_
#define	_RANFunctionDefinition_Report_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include "RIC-Style-Type.h"
#include "RIC-Style-Name.h"
#include "RIC-Format-Type.h"
#include "RANParameter-ID.h"
#include "RANParameter-Name.h"
#include <constr_SEQUENCE.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward definitions */
typedef struct RANFunctionDefinition_Report__ric_ReportStyle_List__Member {
	RIC_Style_Type_t	 ric_ReportStyle_Type;
	RIC_Style_Name_t	 ric_ReportStyle_Name;
	RIC_Style_Type_t	 ric_SupportedEventTriggerStyle_Type;
	RIC_Format_Type_t	 ric_ReportActionFormat_Type;
	RIC_Format_Type_t	 ric_IndicationHeaderFormat_Type;
	RIC_Format_Type_t	 ric_IndicationMessageFormat_Type;
	struct RANFunctionDefinition_Report__ric_ReportStyle_List__Member__ran_ReportParameters_List {
		A_SEQUENCE_OF(typedef struct RANFunctionDefinition_Report__ric_ReportStyle_List__Member__ran_ReportParameters_List__Member {
			RANParameter_ID_t	 ranParameter_ID;
			RANParameter_Name_t	 ranParameter_Name;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} RANFunctionDefinition_Report__ric_ReportStyle_List__Member__ran_ReportParameters_List__Member;
		RANFunctionDefinition_Report__ric_ReportStyle_List__Member__ran_ReportParameters_List__Member) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ran_ReportParameters_List;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RANFunctionDefinition_Report__ric_ReportStyle_List__Member;

/* RANFunctionDefinition-Report */
typedef struct RANFunctionDefinition_Report {
	struct RANFunctionDefinition_Report__ric_ReportStyle_List {
		A_SEQUENCE_OF(RANFunctionDefinition_Report__ric_ReportStyle_List__Member) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} ric_ReportStyle_List;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RANFunctionDefinition_Report_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RANFunctionDefinition_Report;
extern asn_SEQUENCE_specifics_t asn_SPC_RANFunctionDefinition_Report_specs_1;
extern asn_TYPE_member_t asn_MBR_RANFunctionDefinition_Report_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _RANFunctionDefinition_Report_H_ */
#include <asn_internal.h>
