/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-RC-IEs"
 * 	found in "rc.asn1"
 * 	`asn1c -pdu=auto -fno-include-deps -fcompound-names -findirect-choice -gen-PER -gen-OER`
 */

#ifndef	_RANFunctionDefinition_EventTrigger_H_
#define	_RANFunctionDefinition_EventTrigger_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include "RIC-Style-Type.h"
#include "RIC-Style-Name.h"
#include "RIC-Format-Type.h"
#include <constr_SEQUENCE.h>
#include <constr_SEQUENCE_OF.h>
#include "RANParameter-ID.h"
#include "RANParameter-Name.h"
#include "RIC-CallProcessType-ID.h"
#include "RIC-CallProcessType-Name.h"
#include "RIC-CallProcessBreakpoint-ID.h"
#include "RIC-CallProcessBreakpoint-Name.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Forward definitions */
typedef struct RANFunctionDefinition_EventTrigger__ric_EventTriggerStyle_List__Member {
	RIC_Style_Type_t	 ric_EventTriggerStyle_Type;
	RIC_Style_Name_t	 ric_EventTriggerStyle_Name;
	RIC_Format_Type_t	 ric_EventTriggerFormat_Type;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RANFunctionDefinition_EventTrigger__ric_EventTriggerStyle_List__Member;
typedef struct RANFunctionDefinition_EventTrigger__ran_L2Parameters_List__Member {
	RANParameter_ID_t	 ranParameter_ID;
	RANParameter_Name_t	 ranParameter_Name;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RANFunctionDefinition_EventTrigger__ran_L2Parameters_List__Member;
typedef struct RANFunctionDefinition_EventTrigger__ran_CallProcessTypes_List__Member {
	RIC_CallProcessType_ID_t	 callProcessType_ID;
	RIC_CallProcessType_Name_t	 callProcessType_Name;
	struct RANFunctionDefinition_EventTrigger__ran_CallProcessTypes_List__Member__callProcessBreakpoints_List {
		A_SEQUENCE_OF(typedef struct RANFunctionDefinition_EventTrigger__ran_CallProcessTypes_List__Member__callProcessBreakpoints_List__Member {
			RIC_CallProcessBreakpoint_ID_t	 callProcessBreakpoint_ID;
			RIC_CallProcessBreakpoint_Name_t	 callProcessBreakpoint_Name;
			struct RANFunctionDefinition_EventTrigger__ran_CallProcessTypes_List__Member__callProcessBreakpoints_List__Member__ran_CallProcessBreakpointParameters_List {
				A_SEQUENCE_OF(typedef struct RANFunctionDefinition_EventTrigger__ran_CallProcessTypes_List__Member__callProcessBreakpoints_List__Member__ran_CallProcessBreakpointParameters_List__Member {
					RANParameter_ID_t	 ranParameter_ID;
					RANParameter_Name_t	 ranParameter_Name;
					/*
					 * This type is extensible,
					 * possible extensions are below.
					 */
					
					/* Context for parsing across buffer boundaries */
					asn_struct_ctx_t _asn_ctx;
				} RANFunctionDefinition_EventTrigger__ran_CallProcessTypes_List__Member__callProcessBreakpoints_List__Member__ran_CallProcessBreakpointParameters_List__Member;
				RANFunctionDefinition_EventTrigger__ran_CallProcessTypes_List__Member__callProcessBreakpoints_List__Member__ran_CallProcessBreakpointParameters_List__Member) list;
				
				/* Context for parsing across buffer boundaries */
				asn_struct_ctx_t _asn_ctx;
			} *ran_CallProcessBreakpointParameters_List;
			/*
			 * This type is extensible,
			 * possible extensions are below.
			 */
			
			/* Context for parsing across buffer boundaries */
			asn_struct_ctx_t _asn_ctx;
		} RANFunctionDefinition_EventTrigger__ran_CallProcessTypes_List__Member__callProcessBreakpoints_List__Member;
		RANFunctionDefinition_EventTrigger__ran_CallProcessTypes_List__Member__callProcessBreakpoints_List__Member) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} callProcessBreakpoints_List;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RANFunctionDefinition_EventTrigger__ran_CallProcessTypes_List__Member;
typedef struct RANFunctionDefinition_EventTrigger__ran_UEIdentificationParameters_List__Member {
	RANParameter_ID_t	 ranParameter_ID;
	RANParameter_Name_t	 ranParameter_Name;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RANFunctionDefinition_EventTrigger__ran_UEIdentificationParameters_List__Member;
typedef struct RANFunctionDefinition_EventTrigger__ran_CellIdentificationParameters_List__Member {
	RANParameter_ID_t	 ranParameter_ID;
	RANParameter_Name_t	 ranParameter_Name;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RANFunctionDefinition_EventTrigger__ran_CellIdentificationParameters_List__Member;

/* RANFunctionDefinition-EventTrigger */
typedef struct RANFunctionDefinition_EventTrigger {
	struct RANFunctionDefinition_EventTrigger__ric_EventTriggerStyle_List {
		A_SEQUENCE_OF(RANFunctionDefinition_EventTrigger__ric_EventTriggerStyle_List__Member) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} ric_EventTriggerStyle_List;
	struct RANFunctionDefinition_EventTrigger__ran_L2Parameters_List {
		A_SEQUENCE_OF(RANFunctionDefinition_EventTrigger__ran_L2Parameters_List__Member) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ran_L2Parameters_List;
	struct RANFunctionDefinition_EventTrigger__ran_CallProcessTypes_List {
		A_SEQUENCE_OF(RANFunctionDefinition_EventTrigger__ran_CallProcessTypes_List__Member) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ran_CallProcessTypes_List;
	struct RANFunctionDefinition_EventTrigger__ran_UEIdentificationParameters_List {
		A_SEQUENCE_OF(RANFunctionDefinition_EventTrigger__ran_UEIdentificationParameters_List__Member) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ran_UEIdentificationParameters_List;
	struct RANFunctionDefinition_EventTrigger__ran_CellIdentificationParameters_List {
		A_SEQUENCE_OF(RANFunctionDefinition_EventTrigger__ran_CellIdentificationParameters_List__Member) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} *ran_CellIdentificationParameters_List;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} RANFunctionDefinition_EventTrigger_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_RANFunctionDefinition_EventTrigger;
extern asn_SEQUENCE_specifics_t asn_SPC_RANFunctionDefinition_EventTrigger_specs_1;
extern asn_TYPE_member_t asn_MBR_RANFunctionDefinition_EventTrigger_1[5];

#ifdef __cplusplus
}
#endif

#endif	/* _RANFunctionDefinition_EventTrigger_H_ */
#include <asn_internal.h>
