/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "E2SM-RC-IEs"
 * 	found in "rc.asn1"
 * 	`asn1c -pdu=auto -fno-include-deps -fcompound-names -findirect-choice -gen-PER -gen-OER`
 */

#ifndef	_TriggerType_Choice_RRCstate_H_
#define	_TriggerType_Choice_RRCstate_H_


#include <asn_application.h>

/* Including external dependencies */
#include <asn_SEQUENCE_OF.h>
#include "RRC-State.h"
#include "LogicalOR.h"
#include <constr_SEQUENCE.h>
#include <constr_SEQUENCE_OF.h>

#ifdef __cplusplus
extern "C" {
#endif

/* Forward definitions */
typedef struct TriggerType_Choice_RRCstate__rrcState_List__Member {
	RRC_State_t	 stateChangedTo;
	LogicalOR_t	*logicalOR;	/* OPTIONAL */
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TriggerType_Choice_RRCstate__rrcState_List__Member;

/* TriggerType-Choice-RRCstate */
typedef struct TriggerType_Choice_RRCstate {
	struct TriggerType_Choice_RRCstate__rrcState_List {
		A_SEQUENCE_OF(TriggerType_Choice_RRCstate__rrcState_List__Member) list;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} rrcState_List;
	/*
	 * This type is extensible,
	 * possible extensions are below.
	 */
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} TriggerType_Choice_RRCstate_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_TriggerType_Choice_RRCstate;
extern asn_SEQUENCE_specifics_t asn_SPC_TriggerType_Choice_RRCstate_specs_1;
extern asn_TYPE_member_t asn_MBR_TriggerType_Choice_RRCstate_1[1];

#ifdef __cplusplus
}
#endif

#endif	/* _TriggerType_Choice_RRCstate_H_ */
#include <asn_internal.h>
